### ISSUE TITLE
Pillager Outpost + Ocean Monument search doesn't work

### ISSUE THREAD

**Issue by donaastor** [Cubitect/cubiomes-viewer#100]
I ran a search for a Pillager Outpost at distance 1500 from the world origin and then for a Ocean Monument at distance <150 blocks relatively to the Pillager Outpost. The results do not satisfy the condition. When I click on the seeds right in the program, the map rendered tells that there are no couples of a Pillager Outpost and an Ocean Monument that are close to each other. When I replace the Oceam Monument with Igloo, it work perfectly.

**Comment by Cubitect** [comment]
It could be that if there were two or more Outposts and their position got averaged. In the latest release this will no longer happen and each Outpost will be regarded individually.

Also make sure you are not confusing the icons for Outposts and Mansions (they are a bit similar).

**Comment by donaastor** [comment]
Hi! I am not confusing it, I tested it many times. Have you tested to see if you can reproduce my issue?

I am using Arch, on it's AUR there is still the old 1.12 version. I will try to compile the new version when I find some time.

**Comment by Cubitect** [comment]
No, I was not able to reproduce this. Do you still have this issue?

**Comment by Cubitect** [comment]
Tried again and I still cannot reproduce. Given significant changes to the conditions logic since this was opened, I'm gonna assume this is no longer an issue.
