### ISSUE TITLE
Location is relative to filter not working for biome filters

### ISSUE THREAD

**Issue by LindseyLatch** [Cubitect/cubiomes-viewer#102]
Not sure which all filter types are affected, but when I set a biome filter relative to another biome filter, it seems to just defaults to world origin. 

E.g., I set Biome Filter 1:64 to square side of 20 for Jagged Peaks, then set a Biome Filter 1:16 to square side of 3 to find warm ocean relative to the previous filter and it found worlds with warm oceans right near spawn and nowhere near the jagged peaks.

**Comment by Cubitect** [comment]
Biome filters are evaluated for the testing area as a whole and will always yield the center point of that area. To construct a filter that looks at the surroundings of a biomes you have to use reference points, which function as an iterator over an area at a given step size.

However, for your specific case, I think you'll find that jagged peaks and warm oceans require very different climate parameters and will not generate that close to one another. 

Here is the result of a search that I ran for a bit with the relative distance at a much more generous 300 blocks:
[jaggeredpeaks_near_warmocean.txt](https://github.com/Cubitect/cubiomes-viewer/files/8075317/jaggeredpeaks_near_warmocean.txt)

**Comment by Cubitect** [comment]
There was one further problem with biome filters when used as origin for relative structure filters which is fixed now.
