### ISSUE TITLE
Feature suggestion: Allow zooming in/out the map to align to powers of 2 (at certain zoom levels)

### ISSUE THREAD

**Issue by Delvin4519** [Cubitect/cubiomes-viewer#11]
It appears though the default zoom is 1 pixel = 12 blocks, which means it's impossible for it to ever align to 1 block per pixel or 1 chunk per pixel no matter zooming in and out.

**Comment by Cubitect** [comment]
I changed the default zoom to 1 pixel = 16 blocks and you can now also specify a scaling explicitly in the "Goto" dialog.
