### ISSUE TITLE
It can't show nether fortresses in 1.18.

### ISSUE THREAD

**Issue by FragrantOrchid** [Cubitect/cubiomes-viewer#112]
It can't show nether fortresses in 1.18.

**Comment by egor12345567473485** [comment]
is there a version for 1.18.1/1.18?

**Comment by Cubitect** [comment]
It should. (Cannot reproduce.)
Note that some locations of Bastions and Nether Fortresses have switched in 1.18. Maybe you are encountering that?

If you are still confident that this is an issue you experience, you should provide more information, such as: the version of the tool you are using, your operating system, and a screenshot for a seed and location where you would expect a Fortress, but it doesn't show.

**Comment by FragrantOrchid** [comment]
<img width="959" alt="image" src="https://user-images.githubusercontent.com/101559671/163650381-4679bf5b-5b52-47bd-b370-01e5a5f06382.png">
<img width="960" alt="image" src="https://user-images.githubusercontent.com/101559671/163650443-51362235-ffcd-46ea-957a-ff1c8b5c900b.png">
It shows just like this.Only in 1.18 and only in nether.

**Comment by Cubitect** [comment]
The scale at which structures become visible changes between version 1.17 and 1.18, primarily due to performance concerns (1.18+ is orders of magnitude slower than 1.17-). Form the screenshots it looks to me like your zoom is just at the boundary between these scale limits and you should try zooming into the map.

**Comment by mjevans** [comment]
I thought I had this issue too.
It is not obvious that zoom in is required.

**Comment by Cubitect** [comment]
The zoom requirements when structures are visible/hidden has been significantly redesigned and is now configurable in v2.3.0.
The default threshold values are such that everything is visible on the default resolution.
