### ISSUE TITLE
Crashing while searching with Spawn condition without "Stop on results" 

### ISSUE THREAD

**Issue by AutomattPL** [Cubitect/cubiomes-viewer#120]
Hi, I encountered a problem with cubiomes viewer. I have some conditions typed in for 1.16, at least one condition relative to Spawn condition and while everything works while I have option "Stop on results" turned on, but when I turn it off and try to search the seeds, when I click "Abort search" the program stops responding and there's nothing i can do to fix it. 
It happens both on incremental and 48-bit searches, even when I limit maximum searches to number like 5, 20 etc, it still crashes in the same way. The crash doesnt happen without Spawn condition tho. 
My friend reported the same issue while using the program. The crashes occurs both in 2.1.0 and 2.1.1, although it didnt happen to me when i was using version 1.12.1.
Hope it's fixable, I enjoy seedfinding so much with cubiomes peepoHappy

**Comment by Cubitect** [comment]
The deadlock issue should now be fixed in v2.2.0.
