### ISSUE TITLE
Export biomes as image: Exported images are 1 pixel too wide and too tall

### ISSUE THREAD

**Issue by FakenameBill** [Cubitect/cubiomes-viewer#126]
Just like it says in the title, the size of exported images is off by 1 on both axes.

If I want to create an image of a region 24,000 blocks across and 13,500 blocks tall at a 1:4 scale, for example, the resulting image should be 6000 pixels across and 3375 pixels tall. However, if I enter the coordinates X: 0 -> 24000 and Z: 0 -> 13500 into the "export biomes as image" settings, the resulting image is 6001 x 3376 pixels. 

The same applies to other resolutions; for example, at a 1:4 scale, a 4x4 block region should produce an image that is 1x1 pixels; however, the resulting image from "export biomes as image" is 2x2 pixels.

I have tested this at the other scale settings, and the issue applies to all of them.

**Comment by Cubitect** [comment]
All entries in the tool are bounds inclusive by design. So for example a range from 0 -> 8 at scale 1:4 will map as: 
{0,1,2,3} -> 0; {4,5,6,7} -> 1; {8} -> 2.

**Comment by FakenameBill** [comment]
Ah, understood.
Perhaps at some point a note could be added to the "export biomes as image" settings UI saying that the coordinates are inclusive? I'm sure I'm not the only one who will misunderstand.

**Comment by Cubitect** [comment]
I added a clarification at the area entry.
