### ISSUE TITLE
Can't find ancient cities

### ISSUE THREAD

**Issue by DylanDC14** [Cubitect/cubiomes-viewer#127]
doesn't seem to be able to find any ancient cities.

**Comment by DylanDC14** [comment]
also it seems that not every ancient city shown on the map, generates ingame
for example seed: 123567514775977984
ancient city at -208 -224 and ancient city at -736 -352

**Comment by Cubitect** [comment]
The ancient city filter had not been properly added and the generation was still from an earlier snapshot. Should both be fixed now.

**Comment by DylanDC14** [comment]
the search function seems to be fixed :)
but i found that on these seeds: -4107564335137958048 and -3976678470965300625 the ancient city at 0,0 doesn't generate
and i also found that on the seed -3976678470965300625, the ancient city at 144 -160 does not show up on the map
also something maybe minor, the red outline box of the ancient city that shows on the map isnt centered correctly on the central portal of the ancient city ingame (which is what i think you meant to do)

**Comment by Cubitect** [comment]
There was indeed a problem with the offsets which also was responsible for inaccurate generation. Fixed in v2.3.1.
