### ISSUE TITLE
How do I limit the map

### ISSUE THREAD

**Issue by HyPanake** [Cubitect/cubiomes-viewer#131]
I want to limit the map to a certain set of coords because that is where I put the border how can I do this if I could

**Comment by Cubitect** [comment]
There isn't a specialized feature for that. But you can just set the zoom, resize your window and move the vertical splitter in any way you like. You can also set a custom grid spacing in [Edit] > [Preferences] to outline a square area / help you judge the coords better.

**Comment by Cubitect** [comment]
The map can now be undocked and easily resized to any rectangle in v.2.3.0. I believe this is a solution, at least to any practical degree.
