### ISSUE TITLE
(Bug or annoyance) Custom Area search softlocks if coordinates are in wrong order 

### ISSUE THREAD

**Issue by mooing-cowmilk** [Cubitect/cubiomes-viewer#133]
I got around to making an account now to save Dylan the pain lol. Anyways:

The 2 points you choose only work if you list them in a certain order. For example:
![image](https://user-images.githubusercontent.com/106852406/171972216-cf5cb2ba-2b54-4973-818b-1389814374c1.png)

Doing it as the pic above works but doing:
![image](https://user-images.githubusercontent.com/106852406/171972319-46074d6d-ae0d-4305-8965-fca8f72bcefc.png)
will never yield any results even though they are covering the same area.

I believe it is due to it requiring the lower numbers be x1 z1 with the bigger ones being x2 z2. In the sample above it is easy to know which is which. Unfortunately things get confusing when some negs are involved or if one has the pair of coords being x1< x2 but z1 > z2. 

If you forget which way it works it could screw up a search without you realizing, or you have to test the different orders to figure out which is the right one to use. New users can get trip up on this.

**Comment by Cubitect** [comment]
Switching the coords should now work in v2.3.0.

**Comment by mooing-cowmilk** [comment]
Clever solution you did there, at first I thought I typed it in the wrong one to test it
