### ISSUE TITLE
Grid formations on map depending on scale level (with grid selection off)

### ISSUE THREAD

**Issue by mooing-cowmilk** [Cubitect/cubiomes-viewer#135]
Self explanatory. All versions and dimensions
![image](https://user-images.githubusercontent.com/106852406/172021149-ae37f4d0-9373-4bbf-a84d-f4c8179d04bb.png)
![image](https://user-images.githubusercontent.com/106852406/172021197-2fe5b476-bf34-47f9-bbf4-18dd134dc4e8.png)
![image](https://user-images.githubusercontent.com/106852406/172021285-22d8c9dd-f07c-4dcb-a63b-dd6fdbb1fd56.png)
![image](https://user-images.githubusercontent.com/106852406/172021303-21bd9279-c3aa-40d7-94cc-ff7f605826f7.png)

**Comment by Cubitect** [comment]
Should be fixed in v2.3.0.
