### ISSUE TITLE
River/Ocean differences in Cubiomes versus Minecraft

### ISSUE THREAD

**Issue by Robson** [Cubitect/cubiomes-viewer#137]
Just want to begin with a thank you for this tool. I particularly like that the feature set is excellent, it's easy to use and it's very fast.

# Summary

I'm encountering an issue where the rivers and oceans displayed on the Cubiomes map are different to the generation within Minecraft.

# Versions

**Computer**
I'm on Windows 10 Home. 64-bit. 16GB ram.

**Minecraft**
I am using Java Edition 1.19, which is the latest version available at this time. I have no mods installed.

**Java**
The Minecraft debug screen states that the Java version is 17.0.3 64-bit.
When I run the Java Config utility it reports that the latest version of Java is installed. It says the version is 1.8.0_333-b02.

# Examples

## Example 1

**Minecraft**
This world was created in the latest version of Minecraft.
The seed is -584125639337704741
This is from co-ordinates x-25 y+130 z-767.
The world type is normal.
This is in creative mode.
This is facing north.
Here are the [world generating settings](https://github.com/Cubitect/cubiomes-viewer/files/8891740/worldgen_settings_export.txt). The settings are just the defaults.
![Minecraft](https://user-images.githubusercontent.com/3868660/173373222-b973238c-d9e3-4e77-ab03-93a5d71cb6b2.png)

**uNmINeD**
This is just some random application that I found.
It is [version 0.18.14-dev](https://unmined.net/2022/02/23/unmined-0-18-14/).
It is showing the same part of the map that is visible in the screenshot.
Notably uNmINeD is a mapping tool that reads the data files, rather than generating via the seed.
This tool matches the world generated in Minecraft.
![uNmINeD](https://user-images.githubusercontent.com/3868660/173373704-b719a939-7e27-429e-96e8-f5721708a9da.png)

**Cubiomes**
This is showing the same part of the map that is visible in the screenshot.
This is at Y level 30. All Y levels are very similar to this.
The "Biome layer/scale limit" is "Default 1:1".
The selected Minecraft version is 1.19.
Map cache size is 256 MB.
Nothing is selected in the Advanced World Settings.
In Cubiomes the biomes match Minecraft exactly, but we can see that the water is very different.
![Cubiomes](https://user-images.githubusercontent.com/3868660/173375767-2d18ea28-2b88-4e0c-a175-ba2213698902.png)

Quick extra note: in the screenshot above we can see a long island in the south. That shape exists in the Minecraft world, but it is approximately 10 blocks below the water level:
![UnderTheSea](https://user-images.githubusercontent.com/3868660/173381102-b4feae1f-2fcc-47e0-8eb3-3271c329d3da.png)

## Example 2

The example above illustrates the issue being reported, but I'll just briefly show another example:

All settings/etc are the same as the first example, except that this world type is Large Biomes and the screenshots show a substantially bigger area.

**uNmINeD**
This correctly shows the biomes, water, etc.
![uNmINeD2](https://user-images.githubusercontent.com/3868660/173377153-aaa0e9ae-1530-40af-81b8-27f639404e34.PNG)

**Cubiomes**
The land biomes match Minecraft, but the water is very different. As with the first example, there's a lot less water here.
![Cubiomes2](https://user-images.githubusercontent.com/3868660/173377559-50f0ce6f-5acb-4e4c-8216-a58fbecadfc4.PNG)

# Conclusion

I'm unsure as to why this difference is occurring. It's as if Cubiomes thinks the water level is much lower than it is in Minecraft, so it's showing a lot more land where oceans/rivers should be. Perhaps the priority for Cubiomes is speed at the expense of accuracy, so this is known/intentional. Maybe there's no way to determine the water accurately from just the seed.

I wouldn't rule out that I've done something stupid to cause this, but I can't see anything. From extensively playing the world in the second example, I would say that the world is behaving normally and the water seems to be normal.

Very happy to provide further examples, files, information, etc.

**Comment by Robson** [comment]
I've found another seed-to-map tool called ChunkBase, which is producing the same maps as Cubiomes. For example, here's a map for the screenshot directly above this comment:
![ChunkBase](https://user-images.githubusercontent.com/3868660/173418643-c3f9b331-4a42-469c-a9d5-d644494996dc.png)

**Comment by Cubitect** [comment]
Thanks for the detailed report.

Cubiomes shows the biomes, not the generated blocks. There often isn't a perfect correspondence of the biomes and the world generation. You can see the biome you are currently at with the in-game F3 debug overlay.
![2022-06-13_20 43 45](https://user-images.githubusercontent.com/15094581/173424549-7d08c44a-6769-44d4-949b-217c4554bef5.png)

**Comment by Robson** [comment]
Hi Cubitect

Thank you for the quick response. That's unfortunate about the difference between them. Feel a bit strange that Minecraft considers areas of water to be part of the biome, but presumably they have a sensible reason for that. Perhaps it will change in a future version.

It doesn't sound like this is changeable, so I'll close the issue.

Thank you again for the tool.
