### ISSUE TITLE
Feature request: NOT operators

### ISSUE THREAD

**Issue by Anonymous1212144** [Cubitect/cubiomes-viewer#138]
I think a very useful "NOT" operator should also be an option. This mainly arose from trying to compare coordinates of 2 features with limited customizations (e.g. comparing spawn to world origin, where I want seeds where spawn is NOT within 100 blocks of it). This can be implemented as a checkbox in the customization.

**Comment by Cubitect** [comment]
Has been added in 2.3.0.
Also there is now an option to just exclude the origin of the source in a relative condition, which can eliminate the need for a NOT in some circumstances.
