### ISSUE TITLE
Broken dark background in the Condition Editor

### ISSUE THREAD

**Issue by Shadaki** [Cubitect/cubiomes-viewer#140]
Running this program on Linux. Happens only in version 2.2.2, not in 2.2.1.
Screenshot of the issue:
![buggy_behavior](https://user-images.githubusercontent.com/49091098/173883372-50053413-c585-4372-8c37-925dd6d0448d.png)

**Comment by Cubitect** [comment]
This was the result of an attempt to work around a resource loading issue in Qt on Windows. It seems this is inconsistent across platforms and has been reverted in 2.3.0.

**Comment by Shadaki** [comment]
That fixed it, thanks!
