### ISSUE TITLE
Question: Direct download links?

### ISSUE THREAD

**Issue by 2141251436** [Cubitect/cubiomes-viewer#141]
Can I put the download connection directly?

**Comment by 3093FengMing** [comment]
tmd笑不活了，下载链接就在https://github.com/Cubitect/cubiomes-viewer/releases/tag/2.2.2

**Comment by AdminHcat** [comment]
请先学习使用github

**Comment by Cubitect** [comment]
Please only use English.
The releases section has links to the source and executables.
If you want to redirect users from somewhere else I would encourage you to use a link to the main page or releases page though, so users can see and choose from the available versions.
