### ISSUE TITLE
Feature suggestion for End Cities

### ISSUE THREAD

**Issue by MathisTimo** [Cubitect/cubiomes-viewer#144]
Hello, a cool feature that could be usefull would be to see witch end cities contains a ship, similar to chunkbase. And maybe it would be better to put it in a new map selection button (There is already an "End City" button, so you can add an "**End Ship**" button ?) so we can extract only the end city with ship in the Analysis Tab ?

Thank you for still updating this awesome project !

![image](https://user-images.githubusercontent.com/44393289/177219122-58ee98ce-7046-426b-b330-209e9276b561.png)

**Comment by Cubitect** [comment]
Support for End City structure pieces has now been added in v2.4.0, differentiating those with End Ships.
