### ISSUE TITLE
UI freezes when searching with "48-bit family blocks" mode with an exhaustive condition

### ISSUE THREAD

**Issue by 0x000006** [Cubitect/cubiomes-viewer#145]
How to reproduce:
1. Set an exhaustive condition (for example: "Buried treasure x9 (-64, -64), (64, 64)")
2. Set search mode to "48-bit family blocks"
3. Start searching for seeds

Expected behavior:
The UI shows the progress of the search

Actual behavior:
The UI completely freezes until it finds a 48-bit seed that meets the condition(s)

Environment:
Cubiomes-Viewer version: 2.2.2
OS: Windows 10 (21H2)

**Comment by DylanGTech** [comment]
Can confirm this happens on Ubuntu

**Comment by Cubitect** [comment]
The main UI thread was wrongly waiting on the progress report from the 48-bit candidate search thread. This has been fixed v2.3.0.
