### ISSUE TITLE
Feature request - Remove the removed biomes for 1.18+ from the biome color editor gui.

### ISSUE THREAD

**Issue by ILikeTrains27** [Cubitect/cubiomes-viewer#150]
In 1.18, many biomes such as the hills variants were removed from the game, but they still appear in the biome color editor screen. Also, the list of biomes there is in kind of a random order.

**Comment by Cubitect** [comment]
The biome color maps are not specific to a Minecraft version and therefore use the superset of biomes across all versions and dimensions. They are sorted by ascending biome ID, which admittedly is as not as useful anymore in 1.18, but keeps it consistent with the conditions editor.

**Comment by Cubitect** [comment]
The biome color editor now arranges the biomes alphabetically and separates the biomes that are not available in the current map view setting.

**Comment by ILikeTrains27** [comment]
wow that's amazing, thank you so much!
