### ISSUE TITLE
Unable to exclude biomes in pre-1.18 search since Version 2.3.0

### ISSUE THREAD

**Issue by tanyan-tanyan** [Cubitect/cubiomes-viewer#152]
1. Switch to 1.12
2. Set condition to Biomes 1:4
3. Exclude any biome
4. Set range to something like 100-200 blocks
5. Search does not turn up results at all.

I have been able to verify that it works fine on 1.18/1.19 and outputs results, but 1.17 and 1.12 do not output results for example.
Others have been able to reproduce this issue after giving them my reproduction steps.
Someone suggested switching to an older version and it looks like something implemented in Version 2.3.0 broke this, because the version prior to that allows me to exclude biomes on 1.12 just fine.
(Yes, version 2.3.1 is also broken)

**Comment by Cubitect** [comment]
Should work again in patch v2.3.2.
