### ISSUE TITLE
Program Crash when doing nether biome search on 1.16

### ISSUE THREAD

**Issue by mooing-cowmilk** [Cubitect/cubiomes-viewer#163]
seems to only crash on 1.16 . Sometimes it doesn't crash if you make it in 1.17+ then swap to 1.16
Video: https://youtu.be/9p4Dx0BY6LY

**Comment by mooing-cowmilk** [comment]
correction: 1.17 as well, so could be more then just that

**Comment by Cubitect** [comment]
Should be fixed in v2.4.1
