### ISSUE TITLE
[Feature Request] Nether Fortess details support triple or quad cross roads within 32 blocks

### ISSUE THREAD

**Issue by SunnySlopes** [Cubitect/cubiomes-viewer#166]
Since Portal wiske farm becomes available since 1.19, multiple crossroads within 32 blocks of teleporting sphere(Nether) becomes more valuable, especially those who have 3 even 4 crosses clustering together in soul sand valley. So is it possible to calculate the relative position of all 5 crosses in a fortess and tell whether there's any cluster?

**Comment by Cubitect** [comment]
The fortress filter now has an option to select only those that have a 2x2 arrangement of bridge crossings or the starting piece.
Any biome requirements can easily be added by making an additional biome condition at the location of the fortress.

**Comment by SunnySlopes** [comment]
It works! Thanks Cubitect!
