### ISSUE TITLE
1.19 Savanna Village False Positive + Abandoned Village Feature Request

### ISSUE THREAD

**Issue by Nel-S** [Cubitect/cubiomes-viewer#168]
On v2.5.1, Cubiomes Viewer claims 129537913620 has a savanna village at (-1264, 176) despite no such village existing in the actual world. (My guess is this is because the corresponding block, which I'm assuming is where the starting piece is, is in a river biome.)

In addition, while reporting this I thought I would also take a moment to suggest a feature: currently village searches can be set to only include abandoned villages, but there is no way (to my knowledge) to search exclusively for non-abandoned villages. As a result, for example, a search I'm currently running for (among other things) an abandoned village and a non-abandoned village of each biome is turning up several false positives where one or more of the non-abandoned villages are replaced by abandoned ones. Given a three-state checkbox already exists in the biome selection menu, I would imagine this wouldn't be too terribly difficult to implement.

**Comment by Nel-S** [comment]
Update: 59694 also has a false positive village at (64, -960), this time a snowy village whose corresponding block is in an ice spikes biome as opposed to a snowy plains. I am 95% sure that issue (misidentifying what biome the village would attempt to generate within) is the root of the problem.

**Comment by Cubitect** [comment]
I have expanded the "abandoned" village and "end ship" end city specifier to support exclusions in 2.6.0.
The biome check location for villages and bastions depends on the bounding box. This had a slight offset for some starting pieces and rotations and should be fixed now.
