### ISSUE TITLE
[Feature Request] Print Seeds to File rather than matching seeds window.

### ISSUE THREAD

**Issue by klinbee** [Cubitect/cubiomes-viewer#169]
I don't know if I just haven't seen this feature and it is here, but when a large number of seed are printed to the window, it begins to lag a lot and slow down seed finding. I *believe* if it was printed to a text file instead it would help this, but it's just not a feature on here (again, to my knowledge). Would love to have it because it makes seed finding a lot faster at larger scales. In fact, if there is just a way to make it lag less, I don't care how that would also work.

**Comment by Delvin4519** [comment]
I have the same issue with the seed analysis feature, where i want to print directly to file, since the GUI slows down the actual operation.

**Comment by klinbee** [comment]
It seems like this was partially fixed due to the change in 2.6. I just tested it, and it output a million seeds with marginal slow-down.
