### ISSUE TITLE
Feature request: overlay terrain heightmap on biome map

### ISSUE THREAD

**Issue by Delvin4519** [Cubitect/cubiomes-viewer#172]
This feature is in Minemap (MC 1.7/1.12/1.17), and in chunkbase (MC1.18+)

Self explainatory, can display heightmap overlaid on biomes. 

Should be toggled off by default, and disabled when zoom out greater than 16 blocks per pixel.
![image](https://user-images.githubusercontent.com/23464599/198843244-3e74b1c0-3d70-4b8b-9e10-b1419591d51f.png)
![image](https://user-images.githubusercontent.com/23464599/198843295-74ec655c-38b4-4346-a970-031158989a26.png)

**Comment by dragon3025** [comment]
I also thought of this. I was looking for a valley kind of area with specific biomes, and kept having to toggle between alt-d and alt-#.

**Comment by Cubitect** [comment]
Version 3.0.0 now supports an approximation of the surface height as a map layer and filter.

**Comment by Delvin4519** [comment]
Looks good and works well.

It would also be helpful to have a preferences option to toggle a dark/light coloring for low/high terrain, (i.e., dark colors and light colors represent low or high elevations). This is in addition; to angular shading (shading by sun angle) and countour options that exist currently.

**Comment by Delvin4519** [comment]
Updated with additional viewing options in release v3.1, closing this issue.
