### ISSUE TITLE
[Feature Request] add minimum and maximum percentage values to biome conditions

### ISSUE THREAD

**Issue by 0x000006** [Cubitect/cubiomes-viewer#173]
It would be great if we could search for biomes based on a percentage range. For example 60-80% plains so the area is mostly plains.

**Comment by dragon3025** [comment]
I also would like this, but I think it would probably work like in the Biomes tab > statistics tab. That tab helps a little bit, but I tried to find a map that has plenty of cold mountain peaks which is more than 1 biome type, so I ended up importing it to google sheets, added certain columns together, then sorted it.

**Comment by Cubitect** [comment]
Covered by #266.
There is now a biome sample filter in v4.0 that has this function.
