### ISSUE TITLE
Feature Request: Match current scale option for Biome Image export

### ISSUE THREAD

**Issue by mooing-cowmilk** [Cubitect/cubiomes-viewer#175]
Since there is now basically unlimeted zoom, I wanted to use the export image feature but notice it is capped to a max scale of 1:256. Could it be possible to have a option like "from visable" to use the current scale?
![image](https://user-images.githubusercontent.com/106852406/201544080-cb94d739-504b-4ac2-aff8-f34c66b82a4a.png)

**Comment by Cubitect** [comment]
The generation does not support arbitrary scales.
These scale options are dictated by the various methods of generating the biomes, just like the entry layer options (Map > Biome layers). The map viewer also generates only these scales, anything outside or in-between is just normal image zooming.

If you want floating point scaling, or get exactly what you see in the map viewer you better just use a screenshot tool.

**Comment by Cubitect** [comment]
Just to clarify, even if you set the map viewer to a ridiculous scale like 1:10000, the image tiles still use a generation at scale 1:256.
