### ISSUE TITLE
[Feature Request] Adding and multiplying coordinates

### ISSUE THREAD

**Issue by maskersss** [Cubitect/cubiomes-viewer#177]
Add a way to add two coordinates, and to multiply any coordinate by any given number. This will for instance allow to easily find any number of points between two points (for instance to check if I want the path from A to B be through a certain biome/structure).
Also maybe add "point directly between the two points" for convenience, since I can see it specifically being used quite regularly.

**Comment by Cubitect** [comment]
In v3.0.0 you can now define a Lua script where you can check for more complex relations like this. I have even added an example to the script editor that is closely related to specifically this request.

**Comment by maskersss** [comment]
cool, thank you 👍
