### ISSUE TITLE
Is There a Maximum number of seeds that can be listed?

### ISSUE THREAD

**Issue by HoarderofData** [Cubitect/cubiomes-viewer#179]
When cubiommes viewer reaches 63386 it says the maximum number of seeds reached. So does that mean cubiomes viewer can only list 63386 seeds and once?

**Comment by Cubitect** [comment]
The limit is there as a protection, running into it is usually the unintended result of a malformed filter that could freeze the UI or even crash the program if the list was unbounded.

That being said the limit can be changed in the preferences.
