### ISSUE TITLE
Bug: 48 bit family blocks does not increment unless one manually enters in the next structure seed.

### ISSUE THREAD

**Issue by Delvin4519** [Cubitect/cubiomes-viewer#18]
48 bit family blocks does not increment to the next structure seed unless one manually enters in the next structure seed. It seems to just loop back around the same 48bit structure seed.

**Comment by Cubitect** [comment]
It worked for me. Can you give an example (constraints and start) for which this happens?

**Comment by Delvin4519** [comment]
[bug.txt](https://github.com/Cubitect/cubiomes-viewer/files/6037886/bug.txt)

Here is a test file that results in this loop for me.

**Comment by Cubitect** [comment]
Okay thanks, it should be fixed now.

**Comment by Delvin4519** [comment]
it is fixed, resolved, v1.3.1
