### ISSUE TITLE
I softlocked myself kind of? (stuck at max zoom)

### ISSUE THREAD

**Issue by mooing-cowmilk** [Cubitect/cubiomes-viewer#180]
The new nearly uncapped zoom works great, was able to render the full Minecraft world and got screenshots of the end (very cool), nether and overworld. However I closed it at maxed zoom, so for the next secession, it opens with that zoom level. Attempting to change the zoom level freezes the program (unresponsive). I'm able to change the zoom once the max zoom map fully loads (well on the first session anyways, currently waiting for it to fully render to change zoom)

Anyways, may I ask for a button or something to stop loading the map to give process power for me to lower it quicker....

Here are some max zoom pics if your interested:
![A full world 70000 scale grid](https://user-images.githubusercontent.com/106852406/202330782-b9b667d4-c7e7-4d48-87ff-76239bdd8200.PNG)
![A full world 70000 scale](https://user-images.githubusercontent.com/106852406/202330786-569d8f89-8284-44be-b1ee-fca88752218b.PNG)
![image](https://user-images.githubusercontent.com/106852406/202330882-e50470aa-f96c-4b95-9fd3-66915678022a.png)
![image](https://user-images.githubusercontent.com/106852406/202330915-7f74c7bd-66e7-456e-91ef-d2cd48f6373b.png)

**Comment by JakobDev** [comment]
You can delete your config file
