### ISSUE TITLE
How do I use this on MacOS

### ISSUE THREAD

**Issue by 1schlick** [Cubitect/cubiomes-viewer#186]
I followed the build instructions, and what I got was a directory called "build" which is full of .o and .cpp files. Did I do it correctly? How do I launch the app now?

**Comment by aalexr** [comment]
For me, app was in the project folder called `cubiomes-viewer.app`

**Comment by Cubitect** [comment]
The build may not have finished? The .o object files are linked at the end to the cubiomes-viewer executable in the same build directory.

**Comment by Cubitect** [comment]
Experimental dmg files are now provided with the releases.
Otherwise refer to #107.
