### ISSUE TITLE
Large Biomes option not working with 1.18-1.19

### ISSUE THREAD

**Issue by 9cherub** [Cubitect/cubiomes-viewer#189]
I was messing around trying to learn how this amazing tool works, but the "Large Biomes" option doesn't seem to work properly in the latest versions (1.18 and 1.19) but still does in olders:
<img width="1680" alt="1 18" src="https://user-images.githubusercontent.com/119797717/211197580-95e76ea7-08df-40e4-adc5-5daba2e0039b.png">
<img width="1680" alt="1 17" src="https://user-images.githubusercontent.com/119797717/211197585-e05b1f20-d823-4e53-8248-c1601b0f3c6f.png">
(Im on macOS)
I am no expert and I am sorry if this issue had already been reported, or if it is not even an issue..

Anyways, thank you so much for your great work, Cubitect!

**Comment by Cubitect** [comment]
A very recent commit to the trunk added an optimization that was broken for large biomes. Should be fixed now.
