### ISSUE TITLE
toolBar [minor issue] Can't re-open if closed through context menu (besides program restart)

### ISSUE THREAD

**Issue by Sparc343** [Cubitect/cubiomes-viewer#190]
If you close the "toolBar" using the context menu (right clicking) there's no way to re-open it (besides closing and re-starting the app).

**Comment by Sparc343** [comment]
![toolBar](https://user-images.githubusercontent.com/79185973/211436318-40d366d1-8308-4c50-baae-38007abca223.png)

**Comment by Cubitect** [comment]
You should be able to close and reopen the tool bar by right-clicking the menu bar.

**Comment by Sparc343** [comment]
I was thinking about seeing if I could discover how to add it to the "map" menu (but I've just been so busy)! Apologies, I thought I was "blind"! You are correct, context clicking an open area of the menu bar will allow me to "bring it back" without restarting!
