### ISSUE TITLE
I need some way to DM you Cubitect

### ISSUE THREAD

**Issue by mooing-cowmilk** [Cubitect/cubiomes-viewer#192]
I have a intriguing offer for you but it has to be private and I can't find any other of your social media where it possible to DM you. It involves knowing coding for seed finding and some prizes along the way. Maybe afterwards they could be added to cubiome viewer

**Comment by Cubitect** [comment]
You can email me: cubitect at gmail.com.
Usually I check GitHub more often, but I'll look out for a message.

**Comment by mooing-cowmilk** [comment]
I sent the email, github doesn't have DM and you didn't check your discord (or new account?). Hope to see you there

**Comment by Cubitect** [comment]
got it
