### ISSUE TITLE
Links in the 'About' dialog box do not open in browser on click

### ISSUE THREAD

**Issue by Peregrine05** [Cubitect/cubiomes-viewer#194]
Cubiomes Viewer version: 2.6.1-w64
Operating System: Windows 7
Default Browser (is this relevant?): Brave

Clicking on the links in the 'About' dialog box does not open them in a browser as expected; nothing happens instead. The destinations can still be reached by right-clicking on the links and then selecting `Copy Link Location`, and then pasting the URLs into the browser manually.

**Comment by Cubitect** [comment]
Fixed in v3.0.

**Comment by Peregrine05** [comment]
@Cubitect In version 3.0.1-w64, All links open on click except for the [DejaVu Fonts](https://dejavu-fonts.github.io/License.html) link.
