### ISSUE TITLE
48 bit blocks slow on some computers/os's

### ISSUE THREAD

**Issue by 69b69t** [Cubitect/cubiomes-viewer#198]
![image](https://user-images.githubusercontent.com/90358001/213933634-840d802b-7731-41d5-968f-f19ceca2d2d9.png)

(Windows computer, 16 threads)
For example, a simple search looking for 4 mansions within 1024x1024 area around spawn, v2.6.1 does 681G sps while looking for valid structure seeds and around 150k sps checking biomes.
On v3.0.0 though, the checking biomes phase only gets 7k sps. (looking for valid structure seeds is the same speed)
with all threads used, the cpu is never maxed out but on v2.6.1 it would use all the cpu

(Linux, 4 threads)
v2.6.1: 333G sps on structure seed check, 25k sps on biome check
v3.0.0: same structure check speed, and same biome check speed

All searches were done on 1.16, and it seems windows's biome check is slow. incremental does not have this issue

**Comment by Cubitect** [comment]
Should be fixed in v3.0.1. The bug was that every seed in 48-bit mode would check what lua scripts are on the disk. Apparently these file operations are so fast on Linux that it wasn't noticeable.
