### ISSUE TITLE
Take a look at QScintilla

### ISSUE THREAD

**Issue by JakobDev** [Cubitect/cubiomes-viewer#199]
I noticed that you included Lua scripting together with a little self coded code editor in Cubiomes Viewer. however, there is a existing Editor Widget for Qt called [QScintilla](https://www.riverbankcomputing.com/static/Docs/QScintilla/index.html). It has many featured build-in and is available under GPL 3.  You may want to use it over your current implementation. The source code can be found [here](https://www.riverbankcomputing.com/software/qscintilla/download).

**Comment by Cubitect** [comment]
I don't really want to add external dependencies to the project. I could embed the code, like the Lua sources, but QScintilla is very large in comparison. I originally intended to just open a system editor with openUrl(), which is now replaced with a button that opens the lua directory. The little embedded editor is really there just for convenience.

Are there any specific built-in features you are missing?

**Comment by JakobDev** [comment]
I'm not really missing feature. I just know QScintilla and thought, it was better to tell you, so you don't have to spend time to reinvent the wheel.
