### ISSUE TITLE
[Feature suggestion] Move dock/undock button to dropdown menu, hide map bar/map margins

### ISSUE THREAD

**Issue by Delvin4519** [Cubitect/cubiomes-viewer#202]
It seems though the map can't be re-docked after undocking the map. I've checked the menu bar and toolbar and right click but there doesn't seem to be a way to re-dock the map back into the original window. 

EDIT 2: There is, but it requires opening the config dialog after several clicks in the dropdown menus to restore the map to window and hide the map bar. Seems kind of unintuitive for the end user.

Is it possible to move the map docking/undocking feature to the menu bar/toolbar/right click menu? 

This way the map can be put back into the same window after undocking, without having to search the menus for the config dialog to restore the map to window, or hide that map bar. 

It would also allow the default vertical resolution of the map to increase, by removing the map bar entirely by default, which is only used to undock the map. (The map bar consumes 34px on the top and 11px at the bottom, and it is such as default settings)

![image](https://user-images.githubusercontent.com/23464599/214471017-f69d9b75-bd3e-4222-a6b4-fe45a4aabd18.png)

![image](https://user-images.githubusercontent.com/23464599/214475084-8c6298e3-6beb-4a88-b667-607cbfe5d012.png)

EDIT: Found it, silly. closed.

EDIT 2: The existing option allows the map bar to be hidden and to put the map back into the original window after undocking. Takes a while of searching. Not straightforward, reopening this issue.

**Comment by Delvin4519** [comment]
EDIT: Found it, silly. closed.

EDIT 2: The existing option allows the map lbar to be hidden, but it doesn't allow the map to be re-docked after undocking, reopening the issue.

Honestly, the map bar should not be there by default and the undock/dock button should simply be located in the menus. No need for a config button to hide the map bar.

**Comment by Delvin4519** [comment]
Updated in v3.1 to hide the map title bar. Currently the 12/11px top/bottom map margins remain in the default window, but the map can be undocked. 

One note, the undocked map window currently ignores the Windows taskbar when resizing the window, quite problematic since once can drag the bottom of the undocked map window below the Windows taskbar, meaning the undocked map window can't be resized again without adjusting the top margin to resize it again properly.

**Comment by Cubitect** [comment]
The old behavior was the Qt default for a dock-widget. Playing around with it in a Windows VM, it seems that the redocking is triggered with a double click in Windows, but there doesn't seem to be a button for it. On Linux the dock-widget keeps its menu-bar, including a redock button.

Hiding the docking frame, as is now the default in v3.1, is something I implemented by removing the "menu-bar" while undocked.
Regarding the Windows taskbar, I'm fairly confident that there is not much I can do. The behavior seems to vary considerably between platforms and is something handled by Qt. From my understanding, a docking widget is not actually a window and isn't handled by the OS's window manager.

**Comment by Delvin4519** [comment]
Yea, I guess that's the way, anyhow, looks like the functionality works a lot better as of v3.1.1, marking this as resolved and closed.
