### ISSUE TITLE
Feature suggestion: show/hide grid

### ISSUE THREAD

**Issue by Delvin4519** [Cubitect/cubiomes-viewer#21]
As is above, add an ability to show hide the grid on the map

**Comment by Delvin4519** [comment]
Also, one additional note, it appears the grid is only powers of 4 and not powers of 2, since it runs from 512, 2048, 8192, 32768, and 131072. It should go through power of 2 including 1024, 4096, 16384, and 65536.

**Comment by Cubitect** [comment]
I added a grid toggle option to the toolbar, but the map viewer generates the world in tiles and the grid is not an overlay but actually a label and border around those tiles. For performance reasons it makes more sense to segment the world in powers of 4 starting from 512. When zooming, I personally also find it a little confusing when the scale constantly changes, so I actually prefer the power 4 segmentation. I guess I could add an actual grid overlay with customizable segmentation, but unless there is a good reason to use powers of 2 I think I will keep it as it is for now.
