### ISSUE TITLE
[Feature Request] Mark blaze spawners in fortress bounding boxes.

### ISSUE THREAD

**Issue by Adham084** [Cubitect/cubiomes-viewer#210]
This could be an icon on the map or just color the spawner section with a different color than the rest of the fortress.

I am aware of the spawner count feature but showing their location will be easier to understand.

**Comment by Cubitect** [comment]
Added additional 1x1 bounding boxes for the blaze spawners in v3.2.1.

**Comment by Adham084** [comment]
Nice, that was quick.
