### ISSUE TITLE
[Feature suggestion], add "Copy region coordinates" to right click map menu

### ISSUE THREAD

**Issue by Delvin4519** [Cubitect/cubiomes-viewer#211]
I was going to file this prior to release, however, github was down that night and therefore wasn't able to do so.

This is an extremely minor quality of life feature. To my understanding, it's only 2 simple lines to add.

As the title says, when right clicking the map, the right click menu should show an extra option to copy the region file coordinates. Minecraft stores chunks in region files of 512x512 wide. This makes it easy to locate what region file a block or chunk is located in.

For example, block coordinates -2127, -5263 is located in region file -5, -11, in file `r.-5.-11.mca`, therefore, the right click menu shows this is such that can have the option to copy the region file coordinates "Copy region -5 -11".

The region file coordinates is simply FLOOR(coordinates / 512), which is divide the coordinates by 512, and round down to the lower integer. Alternatively, it's 2 to the power of 9.

Perhaps mapview.cpp can be updated with an extra 2 lines at line 335 and 341?

ln336: `QString region  = QString::asprintf("%d %d", p.x >> 9, p.z >> 9);`
ln343 `menu.addAction(tr("Copy region: ")+region, [=](){ this->copyText(region); });`

![image](https://user-images.githubusercontent.com/23464599/219874670-7a515c8f-adc9-42cf-aba0-7c5aa9aa8051.png)

Block 210, -320 is in region file 0, -1.
Block 2050, 1700 is in region file 4, 3.
Block -38574, 23985 is in region file -76, 46.

**Comment by Cubitect** [comment]
Added in v3.2.1. -- I was just creating a patch anyway, since the noise views no longer worked.

**Comment by Delvin4519** [comment]
ah, anyhow, looks fine, marking this as closed and resolved.
