### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Jak2k** [Cubitect/cubiomes-viewer#213]
A 2D (Maybe 3D) preview of the world.

**Comment by tmquan2508** [comment]
This is a good project, but you can add names for the structures

**Comment by Cubitect** [comment]
Reading existing worlds saves is not the goal of this project, if that was your intent.

The current world view shows the generation positions for biomes and structures, as well as the bounding boxes for some of the structures. Anything more detailed goes beyond what is currently feasible. A rough 3D view of the biomes and some of the structure positions may be possible, but it wouldn't give you an accurate view of the world.
