### ISSUE TITLE
Please Support Chinese！

### ISSUE THREAD

**Issue by Inscos** [Cubitect/cubiomes-viewer#214]
Mys Chinese Player！Please！

**Comment by JakobDev** [comment]
Part of #88

**Comment by SunnySlopes** [comment]
> Mys Chinese Player！Please！

you can check my fork for a chinese version

**Comment by JakobDev** [comment]
@SunnySlopes Why did you make a extra fork? Qt has translation support. Just make a PR to add the Chinese translation upstream.

**Comment by Boobies** [comment]
Aw. They even made a cubiomes branch to change the biome strings. That's such a ridiculous way to go about it because those strings could simply be translation keys.

**Comment by SunnySlopes** [comment]
> @SunnySlopes Why did you make a extra fork? Qt has translation support. Just make a PR to add the Chinese translation upstream.

i really don't know there's any qt translation support before. i'm going to learn it, thanks for your suggestions!

**Comment by Cubitect** [comment]
I've fleshed out some some of the issues with the qt translations and added a language option to the preference as well as an incomplete German translation to test with. New languages should ideally just be an appropriate .ts/.qm file in `./rc/lang/` and an entry in `./rc/lang.qrc`

@SunnySlopes 
A new translation (.ts) file can be created and updated with `lupdate` and the translated texts can be edited with Qt Linguist.
The final bundled translations (.qm) file is then created with `lrelease`.

**Comment by SunnySlopes** [comment]
ok, I got it, and I've made a PR for the origin repository for Chinese translation.
