### ISSUE TITLE
[Bug] Keyboard shortcut to zoom in does not work (V3.3.0 RELEASE)

### ISSUE THREAD

**Issue by Delvin4519** [Cubitect/cubiomes-viewer#217]
This is a accessibility feature, useful for some devices, such as portable laptops, etc.

Map scrolling currently requires the use of a mouse, or using the GoTo dialog. 

A set of 2 keyboard shortcuts, say Ctrl J or Ctrl K (like on AMIDST), and/or 2 zoom in/out buttons in the right hand toolbar with the structure/dimension toggles, would make it possible to zoom in or out without using the mouse scroll wheel. It should zoom the map in or out either at power of 2 or Sqrt(2) or equivalent factor multiple of 2^(1/n).

Potential location for on screen buttons for zooming in or out:
![image](https://user-images.githubusercontent.com/23464599/221613508-ecc4e14c-50b8-4aa5-a171-82c0e88e18a1.png)

Top right near the "go to origin reset zoom" button.

**Comment by Delvin4519** [comment]
V3.3.0 RELEASE UPDATE:

The keyboard shortcut to zoom in does not work, since the "+" key is not default on standard keyboards ("=" is).

Either add a second command to the file to allow "=", or "Ctrl" "+",  "Ctrl" "=" (idk which works), or add buttons on the sidebar to do the same function.

Sidebar buttons to zoom in or out would be useful, especially to zoom in or out on touchscreen. The structure on/off toggles already work on touchscreen.

**Comment by Cubitect** [comment]
The zoom now uses the standard Qt shortcuts, the exact key combinations may therefore be platform dependent. (Using "=" is not a good option, as it is layout dependent.)
Additionally zoom buttons can be enabled under "Edit map tools...".
