### ISSUE TITLE
[Support] Changing dimension (to see the nether and the end)

### ISSUE THREAD

**Issue by Adambean** [Cubitect/cubiomes-viewer#223]
Hello,

Not an issue, rather a request for support. Where in the interface can we switch from the overworld dimension to the nether and the end?

I suspect this is possible as the right toolbar has options to show various nether and end features, and the Y axis drop down has got "Nether roof" listed. I really can't find where to view those dimensions in the map view though.

**Comment by mooing-cowmilk** [comment]
![image](https://user-images.githubusercontent.com/106852406/230661609-55d962f2-b5d5-4110-b90e-b9340c53ccf9.png)

**Comment by Adambean** [comment]
Thank you very much @mooing-cowmilk.
*(How did I miss that...)*
