### ISSUE TITLE
Window not showing anymore

### ISSUE THREAD

**Issue by Redstoner-2019** [Cubitect/cubiomes-viewer#224]
For some reason upon launching cubiomes the window is not showing up anymore. The icon is still showing up in the taskbar and the Task Manager says that the app is running normally but still the window is not showing up. When I try to click on the Icon on the taskbar I can see a white window opening to the right side of my screen and disappearing next to my screen.

I have also tried to right click the taskbar and then click "Cascade windows" in case the window just moved off screen, but it is still the same issue.

I have Windows 10 Home, version 22H2, build 19045.2728
Cubiomes Version 3.2.1
CPU: i5-11400
RAM: 64GB

No error messages are shown by Windows and ive tried to redownload cubiomes, but it didnt seem to resolve the issue. But versions before 1.6.0 seem to work.

**Comment by Cubitect** [comment]
In the new 3.3.0 there is a command line option `--reset-all` which might help. It clears all session and preference data and would provide you with a clean start, where the old window position and size won't be restored.

**Comment by nigelqiu** [comment]
I was encountering the same issue on the 3.3.0 build running on Windows 11, but launching once with `--reset-all` argument from the command line resolved it, thanks!

**Comment by japaaaaaaaaaa** [comment]
How do i run it with the command

**Comment by japaaaaaaaaaa** [comment]
> I was encountering the same issue on the 3.3.0 build running on Windows 11, but launching once with `--reset-all` argument from the command line resolved it, thanks!

How did you do it?

**Comment by nigelqiu** [comment]
@japaaaaaaaaaa Open a command prompt in the same directory the cubiomes-viewer executable. An easy way to do so is to navigate to the directory in File Explorer and then type `cmd` in the address bar.

Once you have your command prompt, type in the full executable file name followed by `--reset-all`, then press enter to run the command. For example, the full command with the current executable would be `cubiomes-viewer-3.3.0-w64.exe --reset-all`.

**Comment by japaaaaaaaaaa** [comment]
> @japaaaaaaaaaa Open a command prompt in the same directory the cubiomes-viewer executable. An easy way to do so is to navigate to the directory in File Explorer and then type `cmd` in the address bar.
> 
> Once you have your command prompt, type in the full executable file name followed by `--reset-all`, then press enter to run the command. For example, the full command with the current executable would be `cubiomes-viewer-3.3.0-w64.exe --reset-all`.

thanks
