### ISSUE TITLE
Feature Suggestion: "Exclude All" button in the biome constraint editor

### ISSUE THREAD

**Issue by ellieeet123** [Cubitect/cubiomes-viewer#23]
I think it would be very useful if there could be a button next to the "include all" and "uncheck all" buttons that when you click it, excludes all the biomes. That way it would be easier to set up a constraint to find a specific biome in one area.

**Comment by Vedertesu** [comment]
I really need this feature

**Comment by Delvin4519** [comment]
It would be easy to just do say, if I have a centered square 2, then I can have 9 tiles of Birch Forest (3x3 grid), then I don't have to exclude

**Comment by Vedertesu** [comment]
> It would be easy to just do say, if I have a centered square 2, then I can have 9 tiles of Birch Forest (3x3 grid), then I don't have to exclude

But if you want to search larger areas that have only one or few biomes, this feature helps.

**Comment by Vedertesu** [comment]
1.4.0 added this feature
