### ISSUE TITLE
nether fortess structure indicator makes a mistake in 1.19.4

### ISSUE THREAD

**Issue by SunnySlopes** [Cubitect/cubiomes-viewer#230]
In Cubiomes Viewer 3.2.1, the nether fortess locating at about (0, -100) in the nether of seed 1939297684791900723 is expected to contain a 2x2 arrangement of bridge crossings or start piece in 1.18-1.20. However, when I tried to check it in vanilla 1.19.4, that fortess doesn't contain such a structure.The structure of the fortess in mca (0 ,-1) seems to act properly, containing 2 crossings expected, while the structure lies in mca (-1, -1) doesn't generate as expected. By far, this is the only case I met that seems to went wrong.

**Comment by Cubitect** [comment]
When I check seed 1939297684791900723 in Vanilla (1.18.2, 1.19.4 and 1.20-pre4), the nether fortress at (0, -112) looks just like the outline in Cubiomes Viewer, including the 2x2 arrangement of crossings. Can you give a bit more detail on the exact structure pieces that are different for you, or maybe a screenshot?

**Comment by Cubitect** [comment]
Still not sure regarding the faulty 2x2 arrangements, but there was an issue with the end pieces of fortresses that has been fixed, so I'll assume this is no longer an issue in v3.4. If you find another example, please provide exact locations for the affected pieces and maybe a screenshot.
