### ISSUE TITLE
[Feature Request] Ability To Copy Selected Seed Directly From "Matching Seeds" List

### ISSUE THREAD

**Issue by WorriedAboutClams** [Cubitect/cubiomes-viewer#238]
It'd be nice to be able to directly copy the selected seed from the matching seeds list, rather than needing to select it and then copy it from the seed input box at the top of the program. For example, change the keyboard shortcut for copying the entire list of seed results to ctrl+shift+C and the shortcut for copying only the selected seed to ctrl+C.

**Comment by mooing-cowmilk** [comment]
when you select a seed in the matching seed list, you can do ctrl+c on the map part to copy the seed

**Comment by Cubitect** [comment]
In v3.4, ctrl+C will now only copy the active seed, while ctrl+shift+C will copy the whole seed list.
Also, ctrl-C also copies the current seed when map view has the UI focus, as mooing-cowmilk already mentioned.
