### ISSUE TITLE
end city missing

### ISSUE THREAD

**Issue by JustAnOkapi** [Cubitect/cubiomes-viewer#244]
seed: 5582163254331606933
Structure potential:
![image](https://github.com/Cubitect/cubiomes-viewer/assets/39418801/c6daf346-30e2-4b8c-ad4d-58723cad8659)
normal:
![image](https://github.com/Cubitect/cubiomes-viewer/assets/39418801/9882cb2c-3652-4a50-8ea9-17696fe5b28a)
correct from chunkbase:
![image](https://github.com/Cubitect/cubiomes-viewer/assets/39418801/a35df1e3-748f-428a-940e-e2ef815eed71)
the chunk base map matched when you set the chunkbase version to 1.18, any version higher shows the correct end city

the possible end city, that does end up in the game, does not show on cubiomes (right red circle)
might be related to [this fix](https://bugs.mojang.com/browse/MC-238009)

**Comment by Cubitect** [comment]
End city positions should be fixed for 1.19 and 1.20, in release v3.4.
