### ISSUE TITLE
Found seeds didn't meet the condition.

### ISSUE THREAD

**Issue by tsx8** [Cubitect/cubiomes-viewer#246]
![屏幕截图 2023-07-04 164528](https://github.com/Cubitect/cubiomes-viewer/assets/42398191/baac3e28-b829-423d-83a6-a7ee1a8cfeea)

As the screenshot shows, I'm trying to find a seed whose spawn point is in the plain, with a village within 64 blocks.
I use only condition 07,08,09 first to create a seed list, which in [this article](https://www.bilibili.com/read/cv23514852) is mentioned to speed up the search process.
However as you can see, the first 5 seeds couldn't meet the spawn point condition. But the sixth seed is OK.

![屏幕截图 2023-07-04 165325](https://github.com/Cubitect/cubiomes-viewer/assets/42398191/1cc4e780-ee43-4a9b-91c5-f2ed669fc649)

**Comment by ghost** [comment]
Can you provide more information on your problem?
For example, the seeds you are checking, the filters you are using and which version of the application you are using.
