### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by Trumeet** [Cubitect/cubiomes-viewer#25]
Hi, I'm trying to run the pre-compiled binary on Arch Linux but it fails with dependency issues (`cubiomes-viewer-1.4.1-linux: error while loading shared libraries: libwebp.so.6: cannot open shared object file: No such file or directory`) since the only version of libwebp available on Arch Linux is 1.2.0, which has the ABI version of 7 (libwebp.so.7). I want to try to compile this software to make it work on Arch Linux. Also, I'm trying to make a package for it on Arch Linux so I need instructions on compilation. Unfortunately, I see no Makefile nor other compile instructions to build this software. Could you provide some documents to make it? Thanks.

**Comment by Cubitect** [comment]
I added a section to the Readme. I'm not sure what the qt5 development package would be on Arch. Maybe qt5-base? Let me know if it works or if there are problems.

**Comment by Trumeet** [comment]
Thanks. It works perfectly. I'm not sure which one is the qt5 development package as well but I guess it would be `qt5-base`. Thanks for your help.
