### ISSUE TITLE
Locate Climate Extreme's Continentalness is missing its last four octaves

### ISSUE THREAD

**Issue by Nel-S** [Cubitect/cubiomes-viewer#253]
After following the logic in Cubiomes' climate initialization code, I'm fairly certain that continentalness actually uses 18 octaves:
- the fourteen octaves listed under Locate Climate Extreme's dropdown menu,
- a set of two octaves having amplitude 2/511\*3/2 = 3/511 ~ x0.005871, and lacunarities {large biomes ? 1:16 : 1:4} and {large biomes ? 1:15.7 : 1:3.9}; and
- a set of two octaves having amplitude 1/511\*3/2 = 3/1022 ~ x0.002935, and lacunarities {large biomes ? 1:8 : 1:2} and {large biomes ? 1:7.8 : 1:1.96}.
This can be seen by the fact that, with seed 0 at the origin, the full continentalness is listed as C=-270, but the continentalness using all octaves in the dropdown menu is C.14=-280. Similarly, searching with the 14 octaves misses the fact that 3073 has a continentalness less than -10500 at the origin, while incorrectly stating that 72228 and 80301 do.

Another bug is that currently every octave lists its lacunarity as the one used under Large Biomes, while under Normal Biomes each lacunarity is 4x larger (so 1:1024 for Temperature[0] instead of 1:4096, etc.). From what I can tell the options' texts are currently hardcoded in `src/layerdialog.cpp`, so I'm not sure how feasible it would be to update them whenever Large Biomes is toggled, but if it possible I personally think that would be better as well.

**Comment by Cubitect** [comment]
The limited UI options for the continentalness were originally because their contribution is mostly negligible and you could only map so many shortcuts. The missing octaves are now available without shortcuts.

The octave texts are also now generated and adapt to the world type.
There is also a more detailed summary now for each option that can be viewed in the tooltip.
