### ISSUE TITLE
Hope to support Minecraft Bedrock Edition

### ISSUE THREAD

**Issue by CreeperAWA** [Cubitect/cubiomes-viewer#256]
Hope to support Minecraft Bedrock Edition,thanks.

**Comment by Cubitect** [comment]
This has been requested many times here and on the cubiomes repo https://github.com/Cubitect/cubiomes-viewer/issues/1, https://github.com/Cubitect/cubiomes-viewer/issues/77.
As long as Bedrock does not support modding in a similar way to Java, the required primary research is not realistically feasible to support bedrock. And even if it did, I don't really have the means nor interest in maintaining it myself, so Bedrock is unlikely to ever be supported.
