### ISSUE TITLE
[Question] What does Biome 1:X mean?

### ISSUE THREAD

**Issue by MichaelBufardeci** [Cubitect/cubiomes-viewer#265]
What is the difference between Biome 1:4 and Biome 1:256? Does it just affect the size of the search area or does it change the search itself?

**Comment by black-backdoor** [comment]
I think it just means that the values are multiplied by the factor X.

In the menu there is the text "Location (coordinates are multiplied by x 256)" when I select Biomes 1:256

**Comment by Cubitect** [comment]
The scale indicates how many blocks there are for each coordinate increment.

Examples:
The coordinate (0, 1000) at scale 1:4 maps to the block position (0, 4000). 
An area from (-100, -100) to (100, 100) at scale 1:4 corresponds to the blocks that range from (-400, -400) -> (403, 403).

Historically, biomes were generated in a value map that would be up-scaled while the biome layers were applied.
At scale 1:1024 only the temperature categories are set, as to prevent hot and cold climates from bordering.
At scale 1:256 the major biome types are decided, such as forest, desert, jungle etc.
At scale 1:64 most of the biome variants are applied, such as desert hills and desert lakes.
At scale 1:16 beach biomes and smaller biome patches are added.
At scale 1:4 the biome generation is finished.

For more detail on the possible biomes in these MC versions, you should look for the available biomes in the condition editor, as well as the tool-tip on those biome checkboxes.

With the new noise-based biome generation the scaling factor no longer corresponds to specific generation layers, and will not affect which biomes can occur. Instead, it just controls the spacing of the sampling positions.
You can see the biome layers in Cubiomes Viewer under Layer > Display Options... > "Biome scale".

Note that the in-game biome generation stops at scale 1:4 for most things, such as world generation, spawning behavior etc. The final up-scaling to 1:1 is mostly just visual. (This is true for both the old and new generation.)

I'm currently planning a change to the condition input, so the conditions will be entered with a block area range and the scale will be applied internally during the search. I'm hoping that will reduce some of the confusion regarding this.

**Comment by Cubitect** [comment]
All scaled conditions have been redesigned in version 4.0. All coordinates and area entries are now measured in meters (blocks).
The condition-specific scales will be processed internally instead.
