### ISSUE TITLE
[Feature Request] Filter by Proportion of Biomes

### ISSUE THREAD

**Issue by LordSicarious** [Cubitect/cubiomes-viewer#266]
Recently I've been using Cubiomes quite a lot, and a filter that I've found myself doing manually quite a lot is "judging how much of this area is the target biome(s)." At the moment, the only filters are binary, checking the existence of a biome or not. It's also possible to make an "all biomes must by X" filter by excluding all other biomes. However, there are many scenarios where it would be more useful to allow some more tolerance in this regard.

For instance:
-  Finding islands and peninsulas. An "island" of a particular biome is very difficult to locate at present time, as you can only check for the presence of a nearby ocean, or try to construct some awkward box where you say "these lines must be ocean", improperly excluding weirdly shaped islands. It would be far superior to say "80% of target region must be ocean biomes."
- Other biome enclaves are also difficult to find at present. For instance, finding a pocket of cherry grove, surrounded by a large mass of mountains. Or finding a small pocket of Basalt Delta surrounded by Soul Sand Valley, to make a perfect Magma Cube farm without going above the Nether Roof.
- Easily Spawn-Proofed Area. There are a lot of technical usecases where certain biomes might be preferable for spawn-proofing purposes. But it doesn't need to be 100%. Finding a seed where very little effort is required to proof your Spawn Chunks against passive mobs, for instance: if you set the filter to _only_ allow no-passive biomes, you will miss seeds which have a small (and potentially desirable) pocket of plains inside them, or simply _almost_ completely spawnproof.
- Desiring large areas of mixed biomes. For instance, you might want a large plains or savanna at spawn, _or some mix of the two._ But not want to designate the entire spawn as _only_ being plains or savanna. This would address that issue.
- You might want to avoid large patches of a particular biome, but not avoid the biome _completely,_ which you could do by demanding that 90% of the target area is made up of other biomes.

My suggestion for implementation is that you would have a selection of biomes to include, and then a slider where you can specify the minimum proportion that those biomes must make up in total. For example, a selection of "Warm Ocean, Lukewarm Ocean, Deep Lukewarm Ocean, 50%" would filter only for seeds where at least 50% of the target area is any of those ocean types. This data is already available by doing biome analysis, however there is is not a filterable target for now, making seedhunting on that basis slow and tedious.

**Comment by Cubitect** [comment]
In version 4.0, there is now a Biome Samples filter, which takes pseudo-random samples of the biomes in an area and checks that a minimum proportion of the biomes are part of an allowed biome set.
This is a convenient way to make fuzzy biome checks that are fairly performance friendly.
