### ISSUE TITLE
Feature suggestion: Add an option to export some data to CSV

### ISSUE THREAD

**Issue by MathisTimo** [Cubitect/cubiomes-viewer#27]
Similar to #13, it could be very helpful to have an export tab, from which we can select what to export (like stronghold, dungeons...) and that generates a CSV file. This file can after be used in other software or to do some calculations in Spreadsheets.

And also do you plan to add the end dimension and end structures in the future ? (I saw that the nether is a bit more complex cause biomes are in 3D)

Thanks

**Comment by Boobies** [comment]
The biome distribution is not 3D. It's firmly 2D, except slightly fuzzed in a 3D shape. But making chit chat here is like asking the police how they've been doing in your signed statement.

**Comment by Cubitect** [comment]
I added an export function to the analysis tab. However, currently the analysis looks for all the supported structures with no configuration beyond the area size. I might make the analysis depend on the selected structures in the viewer options in future versions, that way you would have a way to select what structures to find and export.

I want to support the Nether and End at least to some extent eventually, although I am not sure what shape that will take yet. Also I would consider the 1.16 Nether biome generation as 3D. The biome noise varies in the vertical just as much as in the horizontal. However, the y=0 plane has a special role as it determines the structure placement.

**Comment by MathisTimo** [comment]
Thanks that's exactly what I was looking for. This will help a lot of folks out there for sure !
