### ISSUE TITLE
Just a Question.

### ISSUE THREAD

**Issue by GhostCodeByte** [Cubitect/cubiomes-viewer#275]
Hi i'm wondering if i can use the program to find a quad monument on a seed, but i already have a seed so i just wanna find the cords on the world where a quad monument is located.
And realy good program thank you.

**Comment by SunnySlopes** [comment]
<img width="1280" alt="image" src="https://github.com/Cubitect/cubiomes-viewer/assets/49802219/59b91fc6-0f83-42ac-96b9-5d02f06330c2">
You can do it on this tab

**Comment by GhostCodeByte** [comment]
Ok but if i press in Analyze then it stops instantly and nothing shows up

**Comment by SunnySlopes** [comment]
you can change x1 x2 y1 y2，if you still can't find one when you type in 30million, it means there's no such structure in your seed.

**Comment by GhostCodeByte** [comment]
ok but it seems like its not searching because its instant.

**Comment by SunnySlopes** [comment]
it's quite normal, because it doesn't act as you might think.

**Comment by SunnySlopes** [comment]
for short, it only checks the kind of quad-monuments hard-coded in the program, and there's a very fast way that it can finish checking all the posibities within world border(60million * 60 million) almost instantly.

**Comment by Boobies** [comment]
Use GitHub's Discussions feature instead of abusing the bug tracker. This isn't your slumber party where you get to do your chit-chat.

**Comment by SunnySlopes** [comment]
OK, fine.

**Comment by Cubitect** [comment]
As SunnySlopes already explained, the quad-structures analysis in the structures tab can be used to check for quad-huts and quad-monuments in a seed. The check is very fast and covers the entire world, i.e. within 30 million blocks.
Quad-monuments especially are extremely rare. If you have a random seed you can be pretty much certain that it does not have one.
