### ISSUE TITLE
Releases of newer cubiomes viewer version

### ISSUE THREAD

**Issue by SunnySlopes** [Cubitect/cubiomes-viewer#276]
As cubiomes 3.4 has been updated, I could only obtain it by downloading the code and packing it manually by Qt. Could you update a new release for v3.4 and above?

**Comment by MZEEN2424** [comment]
> As cubiomes 3.4 has been updated, I could only obtain it by downloading the code and packing it manually by Qt. Could you update a new release for v3.4 and above?

can you build 3.4 and share exe?

**Comment by SunnySlopes** [comment]
i'm afraid i could only share it under the approval of original author cubitect

**Comment by MZEEN2424** [comment]
> i'm afraid i could only share it under the approval of original author cubitect

bro i have qt and when im gonna build there 5000 error

**Comment by JakobDev** [comment]
> i'm afraid i could only share it under the approval of original author cubitect

This Project is licensed under GPL 3, so you are free to share

**Comment by SunnySlopes** [comment]
OK, fine. I'm going to post one at my fork

**Comment by MZEEN2424** [comment]
> OK, fine. I'm going to post one at my fork

windows detected virus

**Comment by Cubitect** [comment]
Apologies for the lack of binary releases. Version 3.4.1 is now available in the Releases section.
