### ISSUE TITLE
Cubiomes viewer opening in a place where you cannot find

### ISSUE THREAD

**Issue by RagingMalevolence** [Cubitect/cubiomes-viewer#278]
Cubiomes Viewer is opening in a place where you cannot view where it is

**Comment by Cubitect** [comment]
Try resetting the preferences with the command line argument `--reset-all` when starting the program.
On Windows you can do this in the CMD, or from Windows Explorer by navigating to the installation directory (wherever you saved the executable) and enter the program with the arguments in the Path text field:
`cubiomes-viewer-3.4.1-w64.exe --reset-all`

**Comment by Cubitect** [comment]
I suspect that the saved window position somehow become problematic for some users on some systems (maybe a change to monitors?). Version 4.0 will no longer restore the window position by default, which should resolve this issue.
