### ISSUE TITLE
Can't run Cubiomes- Viewer

### ISSUE THREAD

**Issue by AndersStabell** [Cubitect/cubiomes-viewer#281]
I have MinGW and Qt5.0 something and i can't find out how to get qt 5.9 and i still can't run cubiomes viewer all that happens is it creates an empty window.

**Comment by Cubitect** [comment]
Are you trying to compile it yourself? If you just want to run the tool, the executable from the [releases section](https://github.com/Cubitect/cubiomes-viewer/releases) should run as is. It doesn't require you to install anything else.

If you want to compile the tool, you should follow the [build instructions](https://github.com/Cubitect/cubiomes-viewer/blob/trunk/buildguide.md), and I recommend getting Qt via the offline installer (which is only available for Qt 5.12.12) and select MinGW during the install. You can get the source code for cubiomes-viewer with a recursive git clone, or from the source bundle in the releases section (cubiomes-viewer-VERS-src.tar.gz).
