### ISSUE TITLE
Feature request: dungeon finder option

### ISSUE THREAD

**Issue by Some14u** [Cubitect/cubiomes-viewer#29]
Is it possible to add similar functionality to show/check certain dungeons with mob spawners?
I'm interested in searching quad (or even more) spawners within the active range (16+16 blocks) from each another.

**Comment by Cubitect** [comment]
No, dungeons are generated during world population and their placement depends on the actual blocks in the world. Cubiomes only checks for features that can be determined by examining the biomes.
