### ISSUE TITLE
How to clear cache and reset ?

### ISSUE THREAD

**Issue by AstroAbyss** [Cubitect/cubiomes-viewer#296]
I downloaded the .exe version, which is just one file. I need to know where the cache and related settings are stored so I can clear the cache and reset the whole software, I messed up the settings.

**Comment by Cubitect** [comment]
You can start the program from the command line with the option `--reset-all` which will reset everything:
`cubiomes-viewer-static-win.exe --reset-all`

**Comment by AstroAbyss** [comment]
> You can start the program from the command line with the option `--reset-all` which will reset everything: `cubiomes-viewer-static-win.exe --reset-all`

Thanks, the problem has been solved.
