### ISSUE TITLE
Feature suggestion: import a text file of seeds to scan 

### ISSUE THREAD

**Issue by Delvin4519** [Cubitect/cubiomes-viewer#3]
Is it possible to implement a feature to import a text file of a list of seeds and scan that list for a certain subset of features? (Example: You have list of like 1.2 million seeds with 12 eyes of ender, or 2.13 million 32bit seeds with all biomes within 2048), and you want to import that list of seeds to find features around it.)

**Comment by Cubitect** [comment]
Took a little while, but this should now be supported with v1.3.
