### ISSUE TITLE
Feature request: alternative structure seeds support.

### ISSUE THREAD

**Issue by Some14u** [Cubitect/cubiomes-viewer#30]
Currently more than a half of minecraft servers are spigot/paper driven.
As you most likely aware, those have so-called structure seed numbers to control specific structure types distribution. Minecraft also has it's own builtin numbers, but on spigot/paper you're able to alter their values to change generated positions of any feature like villages, monument e.t.c.
As for example, default value for village is 10387312, for desert pyramid is 14357617 and so on. If you change these magic numbers, it would affect where villages and pyramids be generated (aside from the world seed itself).

So i'm asking if it possible to add some kind of settings tab to choose these numbers.

**Comment by Some14u** [comment]
Ah, found all this stuff in finders.h :)
So the request stays the same, could you move these values to preferences tab?

**Comment by Delvin4519** [comment]
Second this one, we could also do quad Mansions, quad every structure, even quad igloo, quad jungle temple, or quad village.

**Comment by Cubitect** [comment]
Version 1.9 now has options for a custom structure salt override. (Edit -> World Settings)
Note that this option only changes the structure salt. Other properties like the region size, chunk gap, or distribution are not configurable as that would break some things.
