### ISSUE TITLE
There were billions of seeds a second, and now suddenly there's not even 200 seeds

### ISSUE THREAD

**Issue by A-LoLo-AI** [Cubitect/cubiomes-viewer#308]
There were billions of seeds a second, and now suddenly there's not even 200 seeds.Why?

**Comment by Cubitect** [comment]
I cannot help if I don't know what you are doing.
If you found a real problem with the search, please create a new issue and provide a detailed description of your search criteria and version, and a screenshot of your search settings.
Ideally, you should also provide the session file for the search (`File...` > `Save session...`).
