### ISSUE TITLE
Losing progress in headless

### ISSUE THREAD

**Issue by zajdov** [Cubitect/cubiomes-viewer#310]
### Expected Behavior
session.save would be updated and discovered seeds appended at the end of the file

### Current behaviour
session.save is reset while only keeping the very last seed

### Environment
- cubiomes-viewer-static-linux 4.0.1
- OS: Linux, Debian 12

### Steps to reproduce
- cubiomes --nogui --session=session.save --out=session.save

### Detailed description
When running cubiomes-viewer in headless mode, the session file is immediately overwritten removing all previously found seeds and only keeping the last discovered seed as progress value.

**Comment by Cubitect** [comment]
As of release 4.1.0 the search progress is now continuously updated in the output file, so a search can be aborted and restarted at any point. Also the result list is now copied to the output file, unless `--reset` is specified as an argument.
