### ISSUE TITLE
ruined portals just dont work

### ISSUE THREAD

**Issue by ghost** [Cubitect/cubiomes-viewer#312]
![graiogh](https://github.com/user-attachments/assets/f3fd7251-cb4a-4952-b421-af6d70305fbc)
![graohoar](https://github.com/user-attachments/assets/70a1d661-b46e-44e1-a2cd-c03039a5f4fd)

**Comment by Cubitect** [comment]
Please provide a seed, location and the game version, otherwise I cannot reproduce a generation issue.
Have you checked underground? Ruined portals can generate as an underground variant.

**Comment by Cubitect** [comment]
User has become a ghost. No reproducible info here. Closing.
