### ISSUE TITLE
terrain generates to 2,147,482,495 instead of 30,000,000

### ISSUE THREAD

**Issue by ghost** [Cubitect/cubiomes-viewer#313]
yeah
also hovering your mouse beyond that displays the biome on the edge, extended infinitely outwards

**Comment by ghost** [comment]
and also the end generation is repeated at the edge
![image](https://github.com/user-attachments/assets/e0f2d540-3e9b-41aa-b7af-d5cab34b88dd)

**Comment by Cubitect** [comment]
Regarding the world border, this has previously been discussed in #204.
Those are outer end rings, which have been part of the game since 1.14. (see https://bugs.mojang.com/browse/MC-159283)
