### ISSUE TITLE
end generation is blocky with artificial detail (also surface height doesnt work)

### ISSUE THREAD

**Issue by ghost** [Cubitect/cubiomes-viewer#314]
![image](https://github.com/user-attachments/assets/66845d6e-14c1-4647-ba5d-17fcc6de3dc5)

**Comment by Cubitect** [comment]
That is the voronoi zoom, which is part of the game. It's not _artificial detail_, but it's relevance has varied over the game versions.
In the latest versions, you can, for the most part, only notice it in the F3 debug screen (note that it changes based on the y-level).
