### ISSUE TITLE
1.21 support

### ISSUE THREAD

**Issue by vico93** [Cubitect/cubiomes-viewer#315]
Does the 1.20 seeds generated on the tool works the same in 1.21.x?

If not, is there any plans to update the tool to latest MC versions?

**Comment by czz4188** [comment]
According to #299 ,the 1.20 generater works well on 1.21 , so there's no recent update plan
(Surely it's annoying to not see the trial chambers)

**Comment by GoldenAureum** [comment]
Hi, i put a seed for 1.21 worldbut it is totally different from the 1.20... send help

**Comment by czz4188** [comment]
I think it's better to send a feedback or repeat #299

**Comment by Cubitect** [comment]
Release 4.1.0 added version 1.21.
Biomes haven't changed since 1.20 (up to the addition of Pale Garden in 1.21.3). So if you have a discrepancy, please make a new report with an example seed, location, version, etc.
