### ISSUE TITLE
terrain going past 256 despite the version being before 1.18

### ISSUE THREAD

**Issue by ghost** [Cubitect/cubiomes-viewer#316]
![image](https://github.com/user-attachments/assets/4f0ec816-4cf0-46e8-9c13-2ba1b7577ed6)

**Comment by Cubitect** [comment]
This can occur when the climate and biomes would suggest such a height, I chose not to clamp the height value in this case. But yes, it is a bad result. The surface height in the Overworld is influenced by lot of things, and should be regarded as an estimate.
