### ISSUE TITLE
ok this isnt even close wtf

### ISSUE THREAD

**Issue by ghost** [Cubitect/cubiomes-viewer#317]
![2024-09-22_17 40 20](https://github.com/user-attachments/assets/5a360656-ddca-41a4-a78b-5da4921401ea)
![image](https://github.com/user-attachments/assets/4a700dc6-b6ff-4be6-b5b6-b1226bf13324)

**Comment by Cubitect** [comment]
Presumably another example for your issue #319?
Again there is not enough information here to reproduce the issue. Maybe you are not looking at a height map, but at one of the climate parameters?

**Comment by ghost** [comment]
it is a height map

**Comment by Cubitect** [comment]
The user has become a ghost, and the issue still has no reproducible info. Closing.
Possibly an issue from Bedrock? Cubiomes only supports Java Edition.
