### ISSUE TITLE
i cant search for any biomes in old versions for some reason

### ISSUE THREAD

**Issue by ghost** [Cubitect/cubiomes-viewer#318]
it just says "biome condition with id 01 includes 1 biome that does not generate in MC 1.6" (the biome is ocean)

**Comment by ghost** [comment]
alright so i just discovered it just doesnt work at all for anything on any version ever, this happened just now and it worked perfectly before
![image](https://github.com/user-attachments/assets/2376eba5-8296-4f5f-8607-bd40c8d3e971)

**Comment by ghost** [comment]
no, removing the condition or restarting cubiomes does not fix it

**Comment by ghost** [comment]
what the fuck why does it save when i remove then redownload it

**Comment by Cubitect** [comment]
Duplicate of #295
Should be fixed in 4.1.0
