### ISSUE TITLE
it doesnt consider ice to be a surface it seems

### ISSUE THREAD

**Issue by ghost** [Cubitect/cubiomes-viewer#320]
![2024-09-23_17 34 42](https://github.com/user-attachments/assets/a14bda1b-2a6f-4d46-8567-ca31bb43a918)
![image](https://github.com/user-attachments/assets/c8602270-4726-460e-9b1e-dc2bc292a2f4)

**Comment by Cubitect** [comment]
The approximate surface height is based on the climate and biomes, and gives an indication where solid blocks start to generate in the early stages of the world generation. Water and ice is affected by the sea level, which is something else.
So yes, this is intentional.
