### ISSUE TITLE
it literally just lied

### ISSUE THREAD

**Issue by ghost** [Cubitect/cubiomes-viewer#327]
![image](https://github.com/user-attachments/assets/a607f28e-78ed-4177-ad85-f197874c03a6)
![2024-10-05_17 32 40](https://github.com/user-attachments/assets/6009892f-61d6-449a-87fa-6466a0a5e60a)

**Comment by Cubitect** [comment]
The location for the stronghold is correct.

![2024-10-07_22 09 14](https://github.com/user-attachments/assets/8e986d6d-51cc-43fb-8a41-7a25dfeec7e0)

I don't know why your world does not have one. Maybe you are using mods that influence the world generation, or you generated the terrain in another version.

In either case, please test that issues with the world generation are reproducible in a new world created with the vanilla game before reporting.
