### ISSUE TITLE
this is the most its ever lied

### ISSUE THREAD

**Issue by ghost** [Cubitect/cubiomes-viewer#328]
![2024-10-11_16 30 14](https://github.com/user-attachments/assets/fd026156-a98f-43cb-859e-3167fa441c20)
![image](https://github.com/user-attachments/assets/9039fa73-b21e-4b4e-9456-0c0a9b9688f4)

**Comment by Cubitect** [comment]
I'm guessing that's Bedrock. Cubiome's only supports Java Edition.
Also, no instructions to reproduce. Closing.
