### ISSUE TITLE
Unable to build version 1.4.1 from source

### ISSUE THREAD

**Issue by JakobDev** [Cubitect/cubiomes-viewer#35]
I'm currently trying to pack cubiomes-viewer for the [AUR](https://aur.archlinux.org/). AUR packages are build from source, so I try to build the 1.4.1 source tarball from GitHub releases. I used the latest git from the cubiomes lib, because it does not provide versions, what is really bad if try to pack it. The build of cubiomes-viwer failed:
```
[jakob@Jakobs-PC build]$ make
/usr/bin/uic ../aboutdialog.ui -o ui_aboutdialog.h
/usr/bin/uic ../configdialog.ui -o ui_configdialog.h
/usr/bin/uic ../gotodialog.ui -o ui_gotodialog.h
/usr/bin/uic ../mainwindow.ui -o ui_mainwindow.h
/usr/bin/uic ../protobasedialog.ui -o ui_protobasedialog.h
/usr/bin/uic ../filterdialog.ui -o ui_filterdialog.h
/usr/bin/uic ../quadlistdialog.ui -o ui_quadlistdialog.h
g++ -c -fwrapv -O2 -O3 -Wall -Wextra -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I../../cubiomes-viewer-1.4.1 -I. -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I. -I. -I/usr/lib/qt/mkspecs/linux-g++ -o aboutdialog.o ../aboutdialog.cpp
g++ -c -fwrapv -O2 -O3 -Wall -Wextra -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I../../cubiomes-viewer-1.4.1 -I. -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I. -I. -I/usr/lib/qt/mkspecs/linux-g++ -o configdialog.o ../configdialog.cpp
g++ -c -fwrapv -O2 -O3 -Wall -Wextra -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I../../cubiomes-viewer-1.4.1 -I. -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I. -I. -I/usr/lib/qt/mkspecs/linux-g++ -o gotodialog.o ../gotodialog.cpp
g++ -c -fwrapv -O2 -O3 -Wall -Wextra -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I../../cubiomes-viewer-1.4.1 -I. -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I. -I. -I/usr/lib/qt/mkspecs/linux-g++ -o protobasedialog.o ../protobasedialog.cpp
g++ -c -fwrapv -O2 -O3 -Wall -Wextra -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I../../cubiomes-viewer-1.4.1 -I. -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I. -I. -I/usr/lib/qt/mkspecs/linux-g++ -o filterdialog.o ../filterdialog.cpp
g++ -c -fwrapv -O2 -O3 -Wall -Wextra -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I../../cubiomes-viewer-1.4.1 -I. -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I. -I. -I/usr/lib/qt/mkspecs/linux-g++ -o quadlistdialog.o ../quadlistdialog.cpp
g++ -c -fwrapv -O2 -O3 -Wall -Wextra -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I../../cubiomes-viewer-1.4.1 -I. -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I. -I. -I/usr/lib/qt/mkspecs/linux-g++ -o mainwindow.o ../mainwindow.cpp
g++ -c -fwrapv -O2 -O3 -Wall -Wextra -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I../../cubiomes-viewer-1.4.1 -I. -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I. -I. -I/usr/lib/qt/mkspecs/linux-g++ -o mapview.o ../mapview.cpp
g++ -c -fwrapv -O2 -O3 -Wall -Wextra -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I../../cubiomes-viewer-1.4.1 -I. -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I. -I. -I/usr/lib/qt/mkspecs/linux-g++ -o quad.o ../quad.cpp
../quad.cpp: In member function 'void Level::init4map(int, int64_t, int, int)':
../quad.cpp:222:13: error: 'setupMultiLayer' was not declared in this scope; did you mean 'setupLayer'?
  222 |             setupMultiLayer(g.entry_1,
      |             ^~~~~~~~~~~~~~~
      |             setupLayer
../quad.cpp:233:13: error: 'setupMultiLayer' was not declared in this scope; did you mean 'setupLayer'?
  233 |             setupMultiLayer(g.entry_1,
      |             ^~~~~~~~~~~~~~~
      |             setupLayer
../quad.cpp:244:13: error: 'setupMultiLayer' was not declared in this scope; did you mean 'setupLayer'?
  244 |             setupMultiLayer(g.entry_1,
      |             ^~~~~~~~~~~~~~~
      |             setupLayer
make: *** [Makefile:1392: quad.o] Error 1
[jakob@Jakobs-PC build]$
```
If I use the latest git of cubiomes-viewer everything works without any problem.

**Comment by Cubitect** [comment]
This seems to be a more general problem with GitHub. The auto-generated tarballs strip all versioning info but don't copy the sub-modules so you are stuck with code that doesn't work and needs manual revision fixing. In general cubiomes-viewer will depend on a particular revision of cubiomes which makes the generated source downloads pretty much useless. You have to recursively clone the repo and switch to the correct tag, or manually get the correct revision of cubiomes. Failing that, I might consider manually creating a tarball for new releases, if you really need them.

**Comment by JakobDev** [comment]
Having a buildable source for each version would be great for people who create packages. Creating a tarball which contains the full source on each release could maybe be done with GitHub Actions.

**Comment by Boobies** [comment]
The problem is that you're building packages in a way that was never intended. First, because the head of a branch is different from an actual release; it's not what users should consider a working version of the software or build packages from. Secondly, because you're dealing with Git submodules which won't be included in the archive even though the repository points to the correct version of cubiomes. You can't just download the head of the library and expect them to be in sync. As suggested, recursively cloning the repository is the appropriate way to approach this.

**Comment by Boobies** [comment]
To be more specific, you want to instal Git and run the following command:

`git clone --recursive https://github.com/Cubitect/cubiomes-viewer`

**Comment by Cubitect** [comment]
I agree that a recursive clone should be the preferred way of getting the source, but I went ahead and added a source tarball anyway. Generated with:
```
$ git clone --recursive https://github.com/Cubitect/cubiomes-viewer.git
$ rm -rf cubiomes-viewer/.git
$ tar cvzf cubiomes-viewer-1.5.0-src.tar.gz cubiomes-viewer
```

**Comment by JakobDev** [comment]
Cubiomes Viewer is now on the [AUR](https://aur.archlinux.org/packages/cubiomes-viewer/). Maybe you could link this in your Readme.

**Comment by Boobies** [comment]
> I agree that a recursive clone should be the preferred way of getting the source, but I went ahead and added a source tarball anyway. Generated with:
> 
> ```
> $ git clone --recursive https://github.com/Cubitect/cubiomes-viewer.git
> $ rm -rf cubiomes-viewer/.git
> $ tar cvzf cubiomes-viewer-1.5.0-src.tar.gz cubiomes-viewer
> ```

I suggest `rm -rf cubiomes-viewer/.git*` instead because you haven't stripped `.gitmodules` and `.gitignore` from the source distribution.

EDIT: Haha, and they ended up on AUR as well because the op was in such a hurry to build a package.

**Comment by JakobDev** [comment]
> EDIT: Haha, and they ended up on AUR as well because the op was in such a hurry to build a package.

Not really. Building a AUR package with simple compile instruction and without any patch is really fast if you know what you are doing.

**Comment by Boobies** [comment]
> if you know what you are doing.

Indeed, that's probably the biggest problem. That package has a number of problems that immediately jump out (incorrect licensing information since cubiomes-viewer links against cubiomes which is lincesed against MIT, artificial limitations regarding the architecture, the quirk we've just discussed, as well as a number of other obvious ones). However, this bug tracker is hardly the correct place to talk about Arch packages.
