### ISSUE TITLE
Cubiomes Viewer is placing it's conig file in the current working directory

### ISSUE THREAD

**Issue by JakobDev** [Cubitect/cubiomes-viewer#36]
I noticed that Cubiomes Viewer places his config file into the current working directory. That means that if you run Cubiomes Viewer from different places you will have different config files. It' s better to have a own directory for that like Home/.config/cubiomes-viewer or Home/.local/share/cubiomes-viewer on Linux for that.

**Comment by ellieeet123** [comment]
This seems like a smart idea

**Comment by Cubitect** [comment]
Settings are now all stored in the .config directory (or equivalent) in v1.6.0

**Comment by JakobDev** [comment]
Version 1.6.0 fixed the issue. Thanks.
