### ISSUE TITLE
Feature Suggestion: Adding a new search method, very similar to incremental but with a set lower and upper boundry

### ISSUE THREAD

**Issue by ellieeet123** [Cubitect/cubiomes-viewer#37]
For example, if I wanted to do a search through the entire bedrock seedspace (approx 4.3 billion seeds) then I could set it so that it starts at seed 0, and searches up until it reaches 4.3 billion and then automatically stops.

**Comment by Delvin4519** [comment]
Yea, basically a set min and set max option

**Comment by Cubitect** [comment]
Cubiomes does not support Bedrock. Is there any other good reason why you would want such a feature?
I don't want to just add widgets to the GUI that only make sense for unsupported features. I'm already struggling to minimize the interface space and keep the clutter to a minimum.

**Comment by ellieeet123** [comment]
Yeah, Cubiomes technically doesn't support bedrock however most java seeds can be converted to bedrock and have very similar biome layouts in both versions. This feature would also be useful if you were doing a larger seedfinding project and wanted to find all seeds with a certain restraint between 1 and 10,000,000,000.

**Comment by Cubitect** [comment]
The incremental search (since v1.8) now supports a range option.
(Select **incremental** search mode and press the "**...**" button next to it.)
