### ISSUE TITLE
Feature suggestion: Large Biome option. and switch entire list to Shadow option.

### ISSUE THREAD

**Issue by Killstepz** [Cubitect/cubiomes-viewer#38]
- Search trough seeds but in Large Biome mode
- View the Map in cubiomes in Large Biome option (abit like the switch to shadow seed, but instead add an option to for switch to large biomes)
- an option to change the entire list to shadow seeds, instead of one seed.

**Comment by Cubitect** [comment]
Adding the shadows of all seeds is possible since v1.7.
Keeping issue #48 for the large biomes.
