### ISSUE TITLE
Bug/Feature request: Set cubiomes-viewer to auto save more often

### ISSUE THREAD

**Issue by Delvin4519** [Cubitect/cubiomes-viewer#39]
Some folks use cubiomes to run overnight, which may not be helpful if the machine must shut down unexpectedly.

Right now cubiomes only saves a session when a user had manually closed cubiomes.

Cubiomes should auto save either at a configurable interval (5-20 minutes) or upon finding a viable seed (latter might slow down if a viable seeds loads every second or so)

**Comment by ellieeet123** [comment]
This seems like a very helpful feature

**Comment by Cubitect** [comment]
Added an option for a cyclic autosave of the session data (i.e. the settings on the search-tab, including the result seeds).
