### ISSUE TITLE
Bug: Nether structure displays are incorrect in basalt delta biomes

### ISSUE THREAD

**Issue by ellieeet123** [Cubitect/cubiomes-viewer#45]
So when you have a basalt delta biome on the nether map, it displays bastion locations, and does not display nether fortress locations. However in game it is the opposite, fortresses do generate however bastions do not. Keep in mind that this only affects basalt deltas, all other biomes are working as intended. Should be an easy fix.

**Comment by Cubitect** [comment]
Oops, should be fixed now.

**Comment by ellieeet123** [comment]
Nice, seems to be working
