### ISSUE TITLE
Sunflower plains missing from Rare_biome layer 1:64

### ISSUE THREAD

**Issue by Delvin4519** [Cubitect/cubiomes-viewer#5]
![image](https://user-images.githubusercontent.com/23464599/104336222-2cfb7e00-54c2-11eb-9d80-17ef8274a5ff.png)

Looks like there is a bug with sunflower plains. It appears in both the HillsLayer 1:64 and RareBiomeLayer 1:64 

![image](https://user-images.githubusercontent.com/23464599/104336357-51575a80-54c2-11eb-8748-5676185d2331.png)

**Comment by Cubitect** [comment]
This was a bug in cubiomes, should be fixed now.
