### ISSUE TITLE
Use system theme as default

### ISSUE THREAD

**Issue by JakobDev** [Cubitect/cubiomes-viewer#50]
I noticed that the latest version of Cubiomes Viewer enables the dark theme by default. I#m not fan of theta. Especially on Linux there are many Qt themes. If a user wants a dark theme, he will set a dark theme as global theme. I think programs should follow the system style by default.

**Comment by Cubitect** [comment]
The problem is that OS themes sometimes break things in the GUI. Providing a builtin style sheet means that I have to worry less about broken layouts in other themes, distros and Windows. 
Nevertheless, I have reverted the default to the system theme in v1.9.
