### ISSUE TITLE
Feature Request: Geodes filter

### ISSUE THREAD

**Issue by manuelgrabowski** [Cubitect/cubiomes-viewer#51]
Seeing how Geodes require a player nearby to grow shards, it would be very beneficial to find places with many geodes close to each other. Is it possible to add a filter for geodes, or do they generate in a way that makes that impossible to look for with cubiomes efficient algorithms?

**Comment by Cubitect** [comment]
Unfortunately, Geode generation seems to be more akin to Dungeons, as far as I could tell. As in, there are many generation attempts, but they require specific blocks to generate. A Geode finder would be nice, but it looks like they cannot be found by just examining the biomes with cubiomes.

**Comment by manuelgrabowski** [comment]
That's a shame, but thanks for looking into it and letting me know! :)
