### ISSUE TITLE
Feature Request: Seed-specific biome alignment finder

### ISSUE THREAD

**Issue by Hjaldr** [Cubitect/cubiomes-viewer#52]
I would like to request a feature that allows the user to find specific biome alignment. For example, if I wanted to find a location in my world where there is a mushroom biome with a jungle 500 blocks to the east and a taiga 500 blocks to the north, there could be a function for the seed analysis where you can define a target biome, and secondary target biomes with fixed x,z distances away from the primary target biome. It could then check the biome on the first block on every chunk border, and progressively scan 'outwards' from the spawn until the conditions are met. If the chunk contains the primary target biome, it then checks if the secondary target coordinates correspond with the secondary target biomes, and if yes, a match is found. This would allow one to find locations in their worlds with very specific biome layouts for building projects. It would then return the coordinates of the matches it finds where the biomes are aligned in that way.

**Comment by Cubitect** [comment]
With the introduction of the spiral iterator helper conditions in v3.0.0, all aspects of this are now possible.
