### ISSUE TITLE
Feature Request: Finder for double and triple structure

### ISSUE THREAD

**Issue by Neumann-Kohai** [Cubitect/cubiomes-viewer#58]
Sometimes all quad structure are too far away and a double / triple one closer by would do the job as well. So it would be awesome if you can search (in a given seed) for those structures and this (optinaly) with in a specified area

**Comment by Boobies** [comment]
While there are no specific finders specifically optimized in Cubiomes currently for this purpose, you can definitely do a search for this. Look for one instance of the structure you wish to find, then add another condition for the number of structures you wish to look for relative to the first one. For example, one ocean monument from (-5000, -5000) to (5000, 5000) and 3 ocean monuments within a centered squared side of 256 relative to the first condition will find seeds with triple ocean monuments from (-5000, -5000) to (5000, 5000).

**Comment by Cubitect** [comment]
There are still no designated finders for this, but it has become even more straightforwards with the addition of radial distances for structures.

Marking as closed.
