### ISSUE TITLE
[Feature request] Seed map image exports

### ISSUE THREAD

**Issue by Hjaldr** [Cubitect/cubiomes-viewer#59]
Would it be possible to add a feature to export a mosaic of images from a specific seed for a given area? For example, if I wanted to build a large interactive map I could enter a seed, and export png files for that seed to then create an interactive map. This could be achieved by generating tiles of 4096 by 4096 pixels (aligns with chunk borders). The scale of the export would have to be 1:1, 1:2, 1:4, 1:8 (pixel:blocks) etc, and the user could indicate how large the export would have to be. For example, if it had to be a 50k map, it would export 676 image files (26*26) if the scale is 1:1.

**Comment by craftmybuild** [comment]
Hi Hjaldr.   I am working on something that might be close to what you are looking for.  If you would like to discuss, please reach out.  thunt@craftmybuild.com

**Comment by Cubitect** [comment]
Took a while, but this is now possible with the biome image export in v2.2.0, although it limited to power of 4 scales, 1:1, 1:4, 1:16, 1:64, and 1:256 due to several technical conveniences.
