### ISSUE TITLE
Quad Monument Finder segfaults for larger areas

### ISSUE THREAD

**Issue by Boobies** [Cubitect/cubiomes-viewer#6]
I don't know whether this is a bug in cubiomes-viewer or cubiomes because I haven't tested the latter but if I use a large square size for quad ocean monuments (e.g., 4096), I get a segfault. This won't happen for witch huts. I'm assuming the monument finder requires more memory and you don't check what you get back from malloc, which returns NULL, or something. Using the Linux build.

**Comment by Cubitect** [comment]
I implemented a memory threshold of 1GB for precomputed lists, but the check was faulty.
Should be fixed with release 1.2.1
