### ISSUE TITLE
Loading progress is broken

### ISSUE THREAD

**Issue by Boobies** [Cubitect/cubiomes-viewer#60]
Loading previously saved progress will restart the search. Using the latest release for both saving and loading, 1.9.1.

**Comment by Boobies** [comment]
Also, opening a condition and then closing the window by cancelling will also lose any progress. I lost hours of progress trying to to find something this way. Perhaps the issues are related.

**Comment by PancakeTAS** [comment]
Can confirm, happens to me too

**Comment by Cubitect** [comment]
This should be fixed in 1.10.
