### ISSUE TITLE
Something wrong with the conditions

### ISSUE THREAD

**Issue by Boobies** [Cubitect/cubiomes-viewer#61]
I'm not 100% sure what the issue is because I didn't investigate but there is something super weird going on that I keep noticing. For example, I just did a test search for ideal quad huts with a mushroom biome at spawn. I've used cubiomes before cubiomes-viewer was a thing and I was able to find *a lot* of seeds for this exact search, in the state the the library was about one year ago, I think. The square size is 128 and it's only finding seeds that have quad huts in the first possible location. The seed finder I wrote against cubiomes was able to find many more seeds elsewhere so I know for a fact that they do exist.

There are also other weird things going on. For example, it seems to me like for example normal seeds do not also include ideal seeds, which is not what a quick look over the header file for that constellation suggests (seems like you wanted each constellation to also be inclusive of the "better" ones above it).

Another thing is that the ranges seem off. I've used a seed list with just one seed where two ocean monuments are very close to one another, put in a search a condition for (a) one to be found in a certain range of the spawn point and (b) another to be found relative to the first (by saying I wanted two ocean monuments relative to the first one within a small range). They are super close to each other in Minecraft but cubiomes-viewer does not find the seed unless the suqare size is 928 even though they are both almost entirely inside the despawn sphwere. So that makes no sense.

Some of these should probably be separate bug reports but I figured it might be some other issue with how you read the input or something, considering my previous bug report, and maybe it's not about what you're searching for but how you're telling cubiomes-viewer what the user expects.

**Comment by Boobies** [comment]
If it was not clear what I meant, all the seeds had only this constellation at this exact position even there are way more from (-2^16, -2^16) to( 2^16, 2^16) or whatever it is that's close to that range: [image](https://i.imgur.com/8l6QhKj.png)

**Comment by Cubitect** [comment]
I expect this is no longer an issue in 2.0.

**Comment by Cubitect** [comment]
Due to significant changes to the implementation of conditions since this was opened, I'm assuming this is fixed now.
If there is still an issue like this, please open a new report.
