### ISSUE TITLE
Won't work on arm/aarch64

### ISSUE THREAD

**Issue by PancakeTAS** [Cubitect/cubiomes-viewer#62]
Seems to be an issue with intrin.h (which doesn't exist). 
[Small fix that I did temporarily](https://github.com/MCPfannkuchenYT/cubiomes-viewer/commit/3e480c5281dddc65e7a1a24d83e7da13462ff4c3)

**Comment by Cubitect** [comment]
Fixed: __rdtsc() is no longer being used.
