### ISSUE TITLE
Feature Request: Completeable Ruined Portal

### ISSUE THREAD

**Issue by skycatminepokie** [Cubitect/cubiomes-viewer#65]
The ability to search for Ruined Portals that match the following conditions would be very helpful:
```
Portal Frame has no crying obsidian (not including corners) AND 
     has enough obsidian in chest to complete frame (at least one side) OR 
     has enough lava AND at least 27 iron nuggets (for a bucket) to complete at least one side (ex using 3 left-hand blocks as the right-hand side of the portal)
OR
Chest has at least 27 iron nuggets AND
     Lava + obsidian in chest = 10
```
This could be made more versatile by allowing for customizable requirements. Something similar could also be made for other structure like Strongholds (# of eyes) and loot in other structures (#56).

I know this is a tall request, but it is just a suggestion. Thanks to all the contributors and to Cubitect for all your hard work!

**Comment by Boobies** [comment]
Cubiomes is not designed to be able to do anything like that. It's designed to know how biomes are distributed and which locations are considered for structure placement.

**Comment by Cubitect** [comment]
You might have some luck with a tool like [Minemap](https://github.com/hube12/Minemap) for something like this. But chest loot etc. is outside the scope of what cubiomes is meant to do.
