### ISSUE TITLE
Feature request: Beta 1.8

### ISSUE THREAD

**Issue by Trilon678** [Cubitect/cubiomes-viewer#66]
Is it possible to add beta 1.8 to this program?

**Comment by Delvin4519** [comment]
makes sense tbh, given the terrain gen was updated in beta 1.8, not 1.0

**Comment by FakenameBill** [comment]
Might be a good idea to request this on [Cubitect/cubiomes](https://github.com/Cubitect/cubiomes)

**Comment by Cubitect** [comment]
Thanks to @KaiSandstrom Beta 1.8 is now supported in v3.0.0, but you have to enable experimental MC version support in the advanced world settings.
