### ISSUE TITLE
Feature request: Windows build instructions in README

### ISSUE THREAD

**Issue by kosma** [Cubitect/cubiomes-viewer#69]
I am kindly requesting some human-readable instructions for building the application under Windows, in a way that's fully static. Despite lots of efforts I've not been able to produce a static build - I can get an exe that runs, but can't share it with friends because of DLL hell.

**Comment by Cubitect** [comment]
For a static build you have to build Qt from source, configured for a static installation. Qt provides instructions on their website for this, but be warned that it takes a fair amount of time and trouble shooting to set up and I believe it uses around 10GB of space.
(The precompiled download is essentially just a normal build against a static install of Qt.)

**Comment by kosma** [comment]
Thanks a lot for the info. Would it be a lot of trouble for you to a release a build of the 1.18 version? I can go through the process of building a static version of Qt but perhaps more people could benefit for it?

**Comment by kosma** [comment]
I'm a potato, you already did. Thanks so much!
