### ISSUE TITLE
Bug: Temperature category condition too restrictive for some valid seeds.

### ISSUE THREAD

**Issue by Delvin4519** [Cubitect/cubiomes-viewer#7]
It appears though there are some valid seeds that cannot be searched for due to the message box "temperature category conditions too restrictive for the area".

This happens when a user selects a particular tile for more than half of the searched area. 
Examples where the message box displays include:

- 5 Ocean tiles in a 3x3 area. 
- 9 Hot/Dry tiles in a 3x3 area. 
- 1 Jungle tile at 0,0
- etc

![image](https://user-images.githubusercontent.com/23464599/104529246-47734b80-55d7-11eb-856a-134966c969cc.png)

However, there are indeed valid Minecraft seeds that have a 3x3 or even 5x5 array of Ocean tiles around 0,0. Some seeds do have a 5x5 array of Hot/Dry tiles. I'm sure there may even be a very rare instance of a 7x7 array of 1 particular climate zone, but 5x5 arrays of a particular climate zone is doable and there are more than several seeds where this happens. Below are examples of 3x4 and 4x3 arrays of 1 particular climate zone. Because of the message box displayed above, this prevents users from searching for these particular valid seeds. 
![image](https://user-images.githubusercontent.com/23464599/104529396-a89b1f00-55d7-11eb-873a-2a86d0164d15.png)
![image](https://user-images.githubusercontent.com/23464599/104529538-f9ab1300-55d7-11eb-8213-8743a88d9ebd.png)
![image](https://user-images.githubusercontent.com/23464599/104529644-30812900-55d8-11eb-94f9-481b7ea25a1a.png)
![image](https://user-images.githubusercontent.com/23464599/104530048-1d228d80-55d9-11eb-88fd-c8b371197c28.png)

**Comment by Cubitect** [comment]
For the warning dialog trigger I accidentally counted the area _excluding_ the upper bounds (so `(m-1)*(n-1)` rather than `n*m`). 
I made a new release for the patch.

**Comment by Cubitect** [comment]
Ah there was another problem, that excluded temperatures will also count towards this warning limit which is problematic since there can be more of those than the area size.
Keeping this open until next release.
