### ISSUE TITLE
Feature request/bug: Custom biome colors [buggy in current relase]

### ISSUE THREAD

**Issue by Delvin4519** [Cubitect/cubiomes-viewer#70]
Is it possible to have custom biome colors in the map viewer, using a text file like this one to set the biome colors?

example: biome id number with RGB code:
{ "name":"enrealbiome", "colorMap":[
[ 0, { "r":17, "g":44, "b":239 } ],
[ 1, { "r":121, "g":150, "b":79 } ],
[ 2, { "r":247, "g":243, "b":192 } ],
[ 3, { "r":120, "g":141, "b":119 } ], 

example: biome name with hex code:
    "Vibrant": {
      "OCEAN": "#112cef",
      "PLAINS": "#79964f",
      "SUNFLOWER_PLAINS": "#91ae5b",
      "DESERT": "#f7f2c0",
      "DESERT_LAKES": "#ebf9a7",

**Comment by Delvin4519** [comment]
also, since biomes names changed in 1.13 and 1.18 (so each biome has more than 1 name), please include an example file of what a biome color.txt should look like for cubiomes viewer, with all the biomes 1.0.0 through 1.18+

**Comment by Cubitect** [comment]
There is now an option for custom biome color overrides. The parser is not particular picky regarding the format. Biome IDs and resource names (lower case with underscores) should work, both with 1.13 and 1.18 biome names. The color can be a hex code or a triplet for RGB. So both your examples should work, save for the uppercase biome names. Also each color scheme will need a separate file, so "Vibrant" will not have an effect.

**Comment by Delvin4519** [comment]
doesn't seem to properly register, some biomes load, some stay as the default, others load some different color
[cubiomes_v3test.txt](https://github.com/Cubitect/cubiomes-viewer/files/7672560/cubiomes_v3test.txt)

**Comment by Cubitect** [comment]
Should be fixed in 1.12.1.

**Comment by Xavom** [comment]
I am using the 1.12.1 version of the tool for mc 1.18.
Using biome names does not work as I think intended, For instance if you use:
warm_ocean:[255 0 0] it changes the color of ocean biome. Same for luke_warm_ocean.
sparse_jungle:[255 0 0] it changes the color of jungle biome. Same for bamboo_jungle.
Similarly anything ending with _forest affects only forest biome.

**Comment by Cubitect** [comment]
Tested for the newer versions and it now works for any syntax of the form:
```
4: #FF0000
warm_ocean: [255 0 0]
sparse_jungle 255 0 0
```
