### ISSUE TITLE
[Bugs]Structures generations acts differently from game in 1.18

### ISSUE THREAD

**Issue by SunnySlopes** [Cubitect/cubiomes-viewer#74]
It seems that in 1.18 mojang changed the structures generate in the nether(but it seems that the nether map has nothing different between 1.17 and 1.18 in the program), and when I need to find a bastion, I would usually find a stronghold at the same position, and vice versa.
In the overworld, I found that some structures generated by your algorithm, but in the game it failed to generate.
For example, seed number:-3580177239519567863, the pillager outpost at 576 1296 failed to generate in the game (Because there's an island)
And in seed:7976360984301181268, the mansion at 3408 3888 also failed to generate in the game

**Comment by Cubitect** [comment]
Thank you for the examples. I have updated Fortresses and Bastions, and found a problem with the 1.18 Outposts.
Mansions, unfortunately can't be determined perfectly, but I was able to improve the accuracy.
There will probably be a new minor release with these changes tomorrow.

**Comment by SunnySlopes** [comment]
thanks!

**Comment by SunnySlopes** [comment]
It seems that all bugs I've discovered in 1.18 has been fixed in 1.11.2, so I'll close the issue. Thanks, Cubitect!
