### ISSUE TITLE
Are Nether Biomes & Structures being added in the future?

### ISSUE THREAD

**Issue by Killstepz** [Cubitect/cubiomes-viewer#8]

**Comment by Delvin4519** [comment]
Cubiomes is a standalone library, written in C, that mimics the Minecraft biome and feature generation **(currently only for the overworld)**

**Comment by Cubitect** [comment]
The answer is maybe, but probably not any time soon.
With cave biomes getting implemented, I intend to have another look at 3D biome generation anyway, but for now it's just the overworld.

**Comment by Killstepz** [comment]
Ok thanks for the reply, good to know :) tool's really amazing alrdy for how long its been out, really great job btw keep it up!

**Comment by Vedertesu** [comment]
It got added, can you close this
