### ISSUE TITLE
Reference Point 1:8?

### ISSUE THREAD

**Issue by PancakeTAS** [Cubitect/cubiomes-viewer#80]
From what I have understood a reference point multiplies the coordinates the input value (aka another structure or smth).
Therefore it would be useful to have a way to check at x8 coordinates for nether travel

**Comment by Cubitect** [comment]
You misunderstood, reference points are a tool that becomes necessary if you want to find a cluster of relative conditions, without a defined center.

Example:
If you want to find a village that's in a desert anywhere within 2000 blocks. If you only use a normal village filter, that condition will succeed with the first village it finds and the biome test will only be checked for that particular village. If the biome test fails, then no other villages will be considered.

A reference point can be thought of as a for-loop over an area and provides a potential branching point for the list of conditions. So you might use a reference point covering the entire area and make the village relative to the reference point to catch all desert villages.

The scale of a reference point is in a way the step size for the iteration over the area.

A coordinate multiplier for the coordinate conversion between dimensions does not exist currently, but is a good Idea that will be in the next version.

**Comment by PancakeTAS** [comment]
Thank you very much for explaining this.
