### ISSUE TITLE
 Feature request: User defined option for grid sizing

### ISSUE THREAD

**Issue by Xavom** [Cubitect/cubiomes-viewer#81]
I think it might be nice to have some options for the grid size. Being able to set the minimum grid size to 1024, 2048, 100, 500, 1000, etc. would be useful. Especially when searching seeds with a planned world center of 10000, 10000 so as to align the grid accordingly to share a screen shot as a server seed suggestion. I'd assume that the tool could adjust that minimum if spacing became too small. Currently I am having issues with the grid size being too dense and obscuring when at certain zoom levels in the 1.18 render.  Also, great job on this tool.

![Screenshot from 2021-12-06 17-16-43](https://user-images.githubusercontent.com/17793670/144938066-57ffb754-cffd-4b62-be27-fce4e0e1d295.png)

**Comment by Delvin4519** [comment]
Yea, 1.18's grid seems to be quite broken, it creates too many intervals and lags the map to load. 1.12 map grids and the map itself is fine.

I'd love for the grid run through each power of 2, down to a scale of 16 for zoomed in maps. The maximum zoomed out map obviously would stay the 131072 as it as right now.

**Comment by Cubitect** [comment]
The new release has a custom grid option. However, with that option enabled the grid won't be dynamic and does no longer represent the progress of the tile generation.

**Comment by Delvin4519** [comment]
This issue is related to #203 , and can be closed and marked as resolved alongside #203.
