### ISSUE TITLE
Project Does Not Compile After Recent Changes

### ISSUE THREAD

**Issue by rlvandaveer** [Cubitect/cubiomes-viewer#82]
The project hasn't compiled getting latest from source since shortly after 1.18 support was added. I've tried going back to 1.11.2 but that resulted in different compilation errors. It seems like something wasn't committed.

../src/configdialog.cpp:91:21: error: use of undeclared identifier 'parseBiomeColors'
                n = parseBiomeColors(cols, buf);
                    ^
1 error generated.
make: *** [configdialog.o] Error 1

**Comment by Cubitect** [comment]
That sounds like you are updating cubiomes-viewer without the cubiomes submodule. You could try something like:
```
cd cubiomes; git pull; make clean
```

**Comment by rlvandaveer** [comment]
I appear to have the submodule. I haven't made any changes to the project other than `git pull`. There are (and were) build warnings that Qt hasn't been tested with the version of the Xcode SDK I have installed 12.1. Maybe there was an update there that happened to coincide with your 1.18 updates.

Going back up a directory and pulling only results in the message 'Already up to date.'

**Comment by rlvandaveer** [comment]
> That sounds like you are updating cubiomes-viewer without the cubiomes submodule. You could try something like:
> 
> ```
> cd cubiomes; git pull; make clean
> ```

BTW @Cubitect, this issue eventually resolved itself with no changes on my end. I haven't searched through all your commits but I believe that some files/changes were not committed to the repo.
