### ISSUE TITLE
Quad hut search fails for some (large?) offsets

### ISSUE THREAD

**Issue by PengolodhGoedath** [Cubitect/cubiomes-viewer#83]
Background: I was searching for seeds with a quad hut with a stronghold in range. I found this example seed 42042210985401 for Minecraft 1.18, which has the desired qualities, from another source. In order to find similar seed, I then played with filters and applied them to this seed for evaluation.

Simple searches for quad-huts worked fine, but to my surprise, when I increased the "within centred square of side" option to 96 (about where the outermost strongholds are able to spawn), the seed was no longer successfully detected.

Some more fiddling revealed that up until (and including) "within centred square of side" = 20 accepts the given seed, whereas a value of 21 no longer does.

Works:
![grafik](https://user-images.githubusercontent.com/63369156/145084035-bc28a61f-8df2-44af-b673-085dbaf798a7.png)

Doesn't work:
![grafik](https://user-images.githubusercontent.com/63369156/145083930-30bda234-e78c-46db-a75b-6d0dbe207296.png)

Not sure whether this is a bug in cubiomes-viewer or cubiomes, though.

**Comment by Cubitect** [comment]
The search switches algorithms when the area gets too large to fit into a list in memory. There was a problem with that alternative algorithm that should be fixed now.

**Comment by PengolodhGoedath** [comment]
Yes, it seems to be fixed in 1.12. Thanks for the quick fix!
