### ISSUE TITLE
Support 32-bit Windows

### ISSUE THREAD

**Issue by z0z0r4** [Cubitect/cubiomes-viewer#84]
Cubiomes-viewer does not support 32-bit Windows systems, hope to provide 32-bit cubiomes-viewer in the release.
Thanks!

**Comment by Boobies** [comment]
It should work just fine. Just go ahead and build a 32-bit version of Qt to link against and build the project as usual. It's unreasonable to ask the developer to set up a million toolchains and the accompanying libraries targeting every obscure platform out there.

**Comment by z0z0r4** [comment]
thanks.

**Comment by Cubitect** [comment]
Sorry, but I will agree with Boobies here. 32-bit platforms are pretty much universally getting phased out.
