### ISSUE TITLE
[BUG]Searching for one monument around another one could return random answers

### ISSUE THREAD

**Issue by SunnySlopes** [Cubitect/cubiomes-viewer#90]
I used the scan condition as follow, with the outcomes showing on the right. But the outcomes doesn't seem to meet my input demand.
![situation](https://user-images.githubusercontent.com/49802219/146482265-a9cae6db-f17e-4388-819d-c9255fee37b0.png)

So I tried to find a solution by adding another function finding double monuments, but still failed because I can't figure out how the function isViableStructurePos() works(It always return false in my trial). And the code I added to the file is as follow:
[search.zip](https://github.com/Cubitect/cubiomes-viewer/files/7731836/search.zip)

Thanks for your assistance!

**Comment by Cubitect** [comment]
The problem you are having with that seed is that there are two monuments that satisfy the first condition. The second condition will be relative to the center of both monuments. You can see this if you go into the analysis tab and analyze the condition trigger. 

To avoid this behavior you can use reference points. Here is an example progress file for a double monument search (load with File->Load progress):
[double_monument_search.txt](https://github.com/Cubitect/cubiomes-viewer/files/7739189/double_monument_search.txt)

**Comment by SunnySlopes** [comment]
thank you for your help!
