### ISSUE TITLE
I have compiled this for mac. Should i upload it for mac users? Also theres no icon by default

### ISSUE THREAD

**Issue by FredTheNerd** [Cubitect/cubiomes-viewer#95]

**Comment by MachineRat8** [comment]
I don't know if you should upload this publicly, but I'm on an M1 mac and it doesn't seem to be able to compile (probably because of the different architecture), so can you send it by email to machinerat8.7prdf@aleeas.com? Thank you.

**Comment by HenryXiaoYang** [comment]
Yes please, I'm a mac user and this project is pretty seamless on MacOS.

**Comment by Cubitect** [comment]
I don't have the means to build or test for macOS and I don't feel comfortable accepting builds for the releases.
However, maybe issue #107 can become a help page for this matter.

**Comment by Cubitect** [comment]
I'll close this issue.
If the missing icon is indeed an problem, you can open a separate issue, but I'm not sure how much I'll be able to help. The application should have an icon.

**Comment by SakisakaSuzune** [comment]
Try Whisky. 
https://getwhisky.app/
