### ISSUE TITLE
Feature request: Show biome generation layers

### ISSUE THREAD

**Issue by FakenameBill** [Cubitect/cubiomes-viewer#97]
For versions that use the layered biome system, add a new drop-down menu to to allow the user to select a generation layer to display as the map view. For example, "Layer 18: Deep Ocean" would show the world separated into temperature zones at a 1:256 scale, and "Layer 19: Biome" would show these temperature zones replaced with their respective biome distributions.  Adding such a feature would allow users to more intuitively understand how biomes were generated in these versions.

For versions that use multinoise, showing the individual noisemaps could be a potential use for this menu -- although I'm not familiar enough with Cubiomes' code to know if the way it handles multinoise would allow for this.

**Comment by Cubitect** [comment]
A scale/layer selection is now available in v2.2.0. However, it uses the unification of the layered and noise generators that is also the new primary API of cubiomes. So it doesn't offer the full control over the entry layer and noise parameters that you are asking for, but the scaled biome search filters now have a visual representation in the map view.

A full control over the entry should also be possible to implement, but it's a fair bit messier and probably less useful, beyond the academic interest.

**Comment by Cubitect** [comment]
The noise maps selection has been added in v2.3.0. This is probably as far as this feature is going to be implemented any time soon though.
